// Tiny Gods v0.5 — Ages & Legends
// Adds civilization eras, monuments, prosperity, notable settlements, and a world-era banner.
world.era='WANDERING AGE'; world.eraDay=1; world.eraChanges=0; world.monuments=world.monuments||[];
const tgV5Style=document.createElement('style');tgV5Style.textContent=`#eraBanner{position:absolute;left:50%;top:72px;transform:translateX(-50%);padding:6px 12px;border-radius:999px;font:800 9px ui-monospace,monospace;letter-spacing:.14em;color:#dfffee;pointer-events:none;transition:.4s opacity}.eraFlash{animation:eraPulse 1.5s ease}@keyframes eraPulse{0%{box-shadow:0 0 0 rgba(124,248,199,0)}35%{box-shadow:0 0 35px rgba(124,248,199,.35)}100%{box-shadow:0 0 0 rgba(124,248,199,0)}}`;document.head.appendChild(tgV5Style);
const tgV5Banner=document.createElement('div');tgV5Banner.id='eraBanner';tgV5Banner.className='glass';tgV5Banner.textContent='WANDERING AGE';document.getElementById('wrap').appendChild(tgV5Banner);
function tgV5Era(){let active=world.settlements.filter(s=>!s.abandoned&&s.pop>0),roads=[...world.roadStrength.values()].filter(v=>v>.25).length;if(!active.length)return 'WANDERING AGE';if(active.length<2)return 'HEARTH AGE';if(world.trades<3&&world.pacts<2)return 'CLAN AGE';if(world.trades>=3||roads>=2)return 'ROAD AGE';if(world.splits>=3&&active.length>=4)return 'CITY AGE';return 'CLAN AGE'}
function tgV5Prosperity(s){let ties=world.settlements.filter(o=>o!==s&&!o.abandoned&&tgRel(s,o)>.55).length;return clamp((s.store||0)*.38+Math.min(s.pop,24)/24*.3+ties*.08+(s.culture?.communal||0)*.12,0,1)}
function tgV5Monuments(){for(const s of world.settlements){if(s.abandoned||s.pop<12||!s.culture||s.monument)continue;let p=tgV5Prosperity(s);if(p>.68&&R()<.0012*(.4+s.culture.bold)){let types=['stone ring','memory pillar','great hearth','waystone'];let type=types[Math.floor(R()*types.length)];s.monument={type,day:Math.floor(day)+1};world.monuments.push({s,type,day:Math.floor(day)+1});s.history.unshift(`Raised a ${type} on day ${Math.floor(day)+1}`);log(`♜ ${s.n} raised a ${type}, marking its growing importance.`)}}}
const tgV5BaseUpdate=update;update=function(dt){tgV5BaseUpdate(dt);let era=tgV5Era();if(era!==world.era){world.era=era;world.eraDay=Math.floor(day)+1;world.eraChanges++;let b=document.getElementById('eraBanner');b.textContent=era;b.classList.remove('eraFlash');void b.offsetWidth;b.classList.add('eraFlash');log(`✺ The world entered the ${era}.`)}tgV5Monuments()};
function tgV5WorldTransform(){ctx.translate(W/2,H/2);ctx.scale(camera.z,camera.z);ctx.translate(-world.w/2-camera.x,-world.h/2-camera.y)}
function tgV5Draw(){ctx.save();tgV5WorldTransform();for(const s of world.settlements){if(s.abandoned||s.pop<1)continue;let p=tgV5Prosperity(s);if(p>.6){ctx.strokeStyle=`hsla(${s.hue} 90% 75% / ${.06+p*.08})`;ctx.lineWidth=1;ctx.beginPath();ctx.arc(s.x,s.y,52+p*18,0,TAU);ctx.stroke()}if(s.monument){let x=s.x-9,y=s.y-11;ctx.save();ctx.shadowBlur=12;ctx.shadowColor=`hsla(${s.hue} 90% 75% / .5)`;ctx.fillStyle='rgba(225,215,180,.9)';if(s.monument.type==='stone ring'){ctx.strokeStyle='rgba(225,215,180,.9)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,6,0,TAU);ctx.stroke()}else{ctx.fillRect(x-2,y-8,4,14);ctx.beginPath();ctx.moveTo(x-5,y-8);ctx.lineTo(x,y-14);ctx.lineTo(x+5,y-8);ctx.closePath();ctx.fill()}ctx.restore()}}ctx.restore();let b=document.getElementById('eraBanner');if(b)b.textContent=`${world.era} · SINCE D${world.eraDay}`}
const tgV5BaseDraw=draw;draw=function(){tgV5BaseDraw();tgV5Draw()};
log('✺ Time deepens: settlements can prosper, raise monuments, and carry the world into new ages.');