// Tiny Gods v0.7 — Archaeology & Visible Time
// Buildings gain age cohorts, legacy phases persist, and prominent houses leave compounds.
world._tgV7Arch=world._tgV7Arch||new Map();
function tgV7ArchState(s){let st=world._tgV7Arch.get(s.id);if(!st){st={birth:s.foundedDay||1,cohorts:[],peak:s.peak||s.pop,lastPop:s.pop,legacy:[]};world._tgV7Arch.set(s.id,st)}let target=Math.max(4,Math.min(24,Math.ceil(s.pop/1.8)));while(st.cohorts.length<target){st.cohorts.push({born:Math.floor(day)+1,seed:tgV7Seeded(s.id*101+st.cohorts.length*17),house:null})}if(s.pop<st.lastPop-3&&st.cohorts.length>target){let lost=st.cohorts.slice(target);st.legacy.push(...lost.map(x=>({...x,ruin:true,abandoned:Math.floor(day)+1})));st.cohorts=st.cohorts.slice(0,target)}st.lastPop=s.pop;st.peak=Math.max(st.peak,s.pop);return st}
function tgV7ArchAgeTone(age){if(age>55)return {wall:18,roof:14,crack:.65,moss:.6};if(age>28)return {wall:22,roof:17,crack:.35,moss:.35};if(age>12)return {wall:27,roof:20,crack:.15,moss:.12};return {wall:31,roof:23,crack:0,moss:0}}
function tgV7HouseAssignments(s,st){let houses=[...new Set(world.agents.filter(a=>a.alive&&a.home===s&&a.dynasty).map(a=>a.dynasty))].sort((a,b)=>b.living-a.living);for(let i=0;i<st.cohorts.length;i++){if(i<houses.length*2&&houses.length)st.cohorts[i].house=houses[i%houses.length]}}
function tgV7ArchHut(p,s,i,meta){let age=Math.max(0,(Math.floor(day)+1)-(meta?.born||s.foundedDay||1)),tone=tgV7ArchAgeTone(age),w=38*p.s,h=31*p.s,roof=19*p.s,x=p.x,y=p.y;ctx.save();ctx.shadowBlur=12*p.s;ctx.shadowColor='rgba(0,0,0,.48)';let hue=meta?.house?meta.house.hue:28;ctx.fillStyle=`hsl(${hue} ${meta?.house?20:18}% ${tone.wall}%)`;ctx.fillRect(x-w/2,y-h,w,h);ctx.fillStyle=`hsl(${meta?.house?hue:18} ${meta?.house?32:28}% ${tone.roof}%)`;ctx.beginPath();ctx.moveTo(x-w*.62,y-h);ctx.lineTo(x,y-h-roof);ctx.lineTo(x+w*.62,y-h);ctx.closePath();ctx.fill();if(tone.moss){ctx.fillStyle=`rgba(87,116,76,${tone.moss*.28})`;ctx.fillRect(x-w*.48,y-h*.98,w*.96,3*p.s)}if(tone.crack){ctx.strokeStyle=`rgba(12,10,8,${.18+tone.crack*.22})`;ctx.lineWidth=.7*p.s;ctx.beginPath();ctx.moveTo(x+w*.08,y-h*.9);ctx.lineTo(x+w*.02,y-h*.68);ctx.lineTo(x+w*.1,y-h*.48);ctx.stroke()}ctx.fillStyle='rgba(255,183,94,.52)';ctx.fillRect(x-w*.08,y-h*.48,w*.16,h*.28);if(meta?.house){ctx.strokeStyle=`hsl(${meta.house.hue} 80% 72%)`;ctx.lineWidth=1.4*p.s;ctx.strokeRect(x-w*.57,y-h*1.03,w*1.14,h*1.06)}ctx.restore()}
function tgV7DrawRuins(s,st){for(let i=0;i<Math.min(6,st.legacy.length);i++){let r=st.legacy[i],x=-170+i*54,y=120+(i%2)*34,p=tgV7Proj(x,y);ctx.save();ctx.fillStyle='rgba(103,94,76,.35)';ctx.fillRect(p.x-13*p.s,p.y-8*p.s,26*p.s,8*p.s);ctx.strokeStyle='rgba(160,148,124,.18)';ctx.beginPath();ctx.moveTo(p.x-15*p.s,p.y-8*p.s);ctx.lineTo(p.x,p.y-17*p.s);ctx.lineTo(p.x+12*p.s,p.y-8*p.s);ctx.stroke();ctx.restore()}}
function tgV7HouseCompound(s,st){let houses=[...new Set(st.cohorts.map(c=>c.house).filter(Boolean))].slice(0,2);for(let i=0;i<houses.length;i++){let h=houses[i],members=world.agents.filter(a=>a.alive&&a.home===s&&a.dynasty===h).length;if(members<3)continue;let p=tgV7Proj((i?1:-1)*165,-10+i*65);ctx.save();ctx.strokeStyle=`hsla(${h.hue} 80% 72% / .45)`;ctx.lineWidth=2*p.s;ctx.setLineDash([5*p.s,4*p.s]);ctx.strokeRect(p.x-38*p.s,p.y-28*p.s,76*p.s,36*p.s);ctx.setLineDash([]);ctx.fillStyle=`hsla(${h.hue} 70% 55% / .18)`;ctx.fillRect(p.x-38*p.s,p.y-28*p.s,76*p.s,36*p.s);ctx.fillStyle=`hsl(${h.hue} 80% 78%)`;ctx.font=`${Math.max(7,8*p.s)}px ui-monospace`;ctx.fillText(`♛ ${h.name}`,p.x-34*p.s,p.y-34*p.s);ctx.restore()}}
const tgV7ArchBaseClose=tgV7Close;tgV7Close=function(){let s=tgV7Settlement;if(!s||s.abandoned){tgV7Exit();return}let st=tgV7ArchState(s);tgV7HouseAssignments(s,st);tgV7Ground(s);tgV7Road();let layout=tgV7Layout(s);for(let i=0;i<layout.length;i++){let h=layout[i],p=tgV7Proj(h.x,h.y),meta=st.cohorts[i]||null;tgV7ArchHut(p,s,h.i,meta)}tgV7DrawRuins(s,st);tgV7HouseCompound(s,st);if(typeof tgV7IdentityCenter==='function')tgV7IdentityCenter(s);tgV7Monument(s);tgV7Caravans(s);tgV7Fire(s);tgV7Hits=tgV7People(s);tgV7Trees();tgV7Weather();ctx.fillStyle='rgba(235,255,246,.92)';ctx.font='800 12px ui-monospace';ctx.fillText(`${s.culture?.sigil||'⌂'} ${s.n}`,22,30);ctx.font='9px ui-monospace';ctx.fillStyle='rgba(210,232,224,.66)';let oldest=st.cohorts.length?Math.max(...st.cohorts.map(c=>Math.floor(day)+1-c.born)):0;ctx.fillText(`${s.culture?.name||'settlement'} · pop ${s.pop} · oldest homes ${oldest}d · ruins ${st.legacy.length}`,22,47);if(s.founder)ctx.fillText(`founded by ${s.founder.n}`,22,62)};
log('⌛ Settlements now carry visible age: new construction, old walls, house compounds, and embedded ruins.');