// Tiny Gods v0.9 — Atmosphere & Domains
// Adds procedural village atmosphere, gardens, fences, bridges, caravan bodies and domain-specific divine effects.
function tgV9Rand(n){let x=Math.sin(n*91.733+CFG.seed*.013)*43758.5453;return x-Math.floor(x)}
function tgV9DomainFx(d){let a=d.agent,p=tgV9WorldPoint(a),ar=d.arch,t=performance.now()*.001;if(p.x<-120||p.x>W+120||p.y<-120||p.y>H+120)return;ctx.save();ctx.translate(p.x,p.y-24);ctx.globalCompositeOperation='lighter';ctx.strokeStyle=`hsla(${ar.hue} 90% 72% / .22)`;ctx.fillStyle=`hsla(${ar.hue} 92% 70% / .28)`;if(ar.domain==='root'){for(let i=0;i<6;i++){let an=i/6*TAU+t*.08,r=20+8*Math.sin(t+i);ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(Math.cos(an)*r*.4,Math.sin(an)*r*.4,Math.cos(an)*r,Math.sin(an)*r);ctx.stroke()}}else if(ar.domain==='light'){for(let i=0;i<8;i++){let an=i/8*TAU+t*.12;ctx.beginPath();ctx.moveTo(Math.cos(an)*15,Math.sin(an)*15);ctx.lineTo(Math.cos(an)*32,Math.sin(an)*32);ctx.stroke()}}else if(ar.domain==='memory'){for(let i=0;i<5;i++){let an=t*.18+i*TAU/5,r=22+i*3;ctx.beginPath();ctx.arc(Math.cos(an)*5,Math.sin(an)*4,r,an,an+1.1);ctx.stroke()}}else if(ar.domain==='river'){for(let i=0;i<3;i++){ctx.beginPath();for(let x=-28;x<=28;x+=4){let y=(i-1)*8+Math.sin(x*.22+t*2+i)*4;let xx=x,yy=y;if(x===-28)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)}ctx.stroke()}}else if(ar.domain==='spark'){for(let i=0;i<5;i++){let an=t*1.6+i*1.9,r=18+tgV9Rand(i+a.id)*15;ctx.beginPath();ctx.moveTo(Math.cos(an)*7,Math.sin(an)*7);ctx.lineTo(Math.cos(an+.25)*r*.55,Math.sin(an+.25)*r*.55);ctx.lineTo(Math.cos(an)*r,Math.sin(an)*r);ctx.stroke()}}else if(ar.domain==='road'){ctx.setLineDash([4,5]);ctx.beginPath();ctx.arc(0,0,26+Math.sin(t)*4,0,TAU);ctx.stroke();ctx.setLineDash([])}else if(ar.domain==='hearth'){for(let i=0;i<7;i++){let an=i/7*TAU+t*.04;ctx.beginPath();ctx.arc(Math.cos(an)*20,Math.sin(an)*12,2.4,0,TAU);ctx.fill()}}ctx.restore()}
const tgV9AtmosBasePantheon=tgV9DrawWorldPantheon;tgV9DrawWorldPantheon=function(){tgV9AtmosBasePantheon();for(const d of world.pantheon||[])tgV9DomainFx(d)};
function tgV9Garden(s){let tier=typeof tgV7ProsperityTier==='function'?tgV7ProsperityTier(s):1,count=2+tier;for(let i=0;i<count;i++){let side=i%2?1:-1,p=tgV7Proj(side*(110+i*18),115+(i%2)*34);ctx.save();ctx.fillStyle='rgba(78,113,61,.36)';ctx.strokeStyle='rgba(170,143,95,.45)';ctx.lineWidth=1*p.s;ctx.fillRect(p.x-24*p.s,p.y-9*p.s,48*p.s,18*p.s);for(let r=-1;r<=1;r++){ctx.beginPath();ctx.moveTo(p.x-20*p.s,p.y+r*5*p.s);ctx.lineTo(p.x+20*p.s,p.y+r*5*p.s);ctx.stroke()}for(let k=0;k<5;k++){ctx.fillStyle=k%2?'rgba(121,170,77,.7)':'rgba(76,145,73,.7)';ctx.beginPath();ctx.arc(p.x-16*p.s+k*8*p.s,p.y-2*p.s,2.4*p.s,0,TAU);ctx.fill()}ctx.restore()}}
function tgV9Fences(s){let tier=typeof tgV7ProsperityTier==='function'?tgV7ProsperityTier(s):1;if(tier<2)return;for(let side of [-1,1]){let p1=tgV7Proj(side*165,150),p2=tgV7Proj(side*190,225);ctx.save();ctx.strokeStyle='rgba(146,111,73,.55)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke();for(let j=0;j<4;j++){let q=j/3,x=lerp(p1.x,p2.x,q),y=lerp(p1.y,p2.y,q);ctx.beginPath();ctx.moveTo(x,y-8);ctx.lineTo(x,y+5);ctx.stroke()}ctx.restore()}}
function tgV9Bridge(){let p=tgV7Proj(0,205);ctx.save();ctx.strokeStyle='rgba(89,132,145,.34)';ctx.lineWidth=22*p.s;ctx.beginPath();ctx.moveTo(p.x-65*p.s,p.y+8*p.s);ctx.quadraticCurveTo(p.x,p.y+16*p.s,p.x+65*p.s,p.y+7*p.s);ctx.stroke();ctx.strokeStyle='rgba(139,104,63,.9)';ctx.lineWidth=10*p.s;ctx.beginPath();ctx.moveTo(p.x-42*p.s,p.y+1*p.s);ctx.lineTo(p.x+42*p.s,p.y+1*p.s);ctx.stroke();ctx.strokeStyle='rgba(201,168,109,.5)';ctx.lineWidth=1;for(let i=-4;i<=4;i++){ctx.beginPath();ctx.moveTo(p.x+i*9*p.s,p.y-4*p.s);ctx.lineTo(p.x+i*9*p.s,p.y+7*p.s);ctx.stroke()}ctx.restore()}
function tgV9VillageGlow(s){let night=.5-.5*Math.cos((day%1)*TAU);if(night<.42)return;let layout=tgV7Layout(s).slice(0,16);for(const h of layout){let p=tgV7Proj(h.x,h.y),g=ctx.createRadialGradient(p.x,p.y-12*p.s,1,p.x,p.y-12*p.s,18*p.s);g.addColorStop(0,`rgba(255,184,90,${.22+night*.25})`);g.addColorStop(1,'rgba(255,130,30,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y-12*p.s,18*p.s,0,TAU);ctx.fill()}}
function tgV9CaravanBodies(s){let cs=world.caravans.filter(c=>c.to===s||c.from===s).slice(0,3);for(let i=0;i<cs.length;i++){let c=cs[i],q=clamp(c.t/c.dur,0,1),y=-145+q*350,x=(i-1)*34,pr=tgV7Proj(x,y);ctx.save();ctx.fillStyle='rgba(104,77,52,.95)';ctx.fillRect(pr.x-11*pr.s,pr.y-6*pr.s,18*pr.s,9*pr.s);ctx.fillStyle=c.kind==='trade'?'#e5bc66':'#9bc8ea';ctx.fillRect(pr.x-7*pr.s,pr.y-11*pr.s,10*pr.s,6*pr.s);ctx.strokeStyle='rgba(231,218,190,.7)';ctx.lineWidth=1.3*pr.s;ctx.beginPath();ctx.arc(pr.x-8*pr.s,pr.y+5*pr.s,4*pr.s,0,TAU);ctx.arc(pr.x+8*pr.s,pr.y+5*pr.s,4*pr.s,0,TAU);ctx.stroke();ctx.restore()}}
const tgV9AtmosBaseClose=tgV7Close;tgV7Close=function(){tgV9AtmosBaseClose();let s=tgV7Settlement;if(!s||s.abandoned)return;tgV9Bridge();tgV9Garden(s);tgV9Fences(s);tgV9CaravanBodies(s);tgV9VillageGlow(s)};
log('✧ Atmosphere deepens: gods radiate their domains, villages gain gardens, fences, bridges, warm windows, and visible caravan bodies.');