// Tiny Gods v0.9 — Cinematic showcase layer
(function(){
world.omens=world.omens||[];
const s=document.createElement('style');s.textContent=`#tg-pantheon{position:absolute;left:18px;top:86px;z-index:88;width:230px;padding:10px;border-radius:14px;background:rgba(4,10,15,.78);border:1px solid rgba(255,255,255,.09);backdrop-filter:blur(12px);font:9px/1.4 ui-monospace;color:#cfe5da}#tg-pantheon b{color:#eafff5;letter-spacing:.1em}#tg-pantheon .god{margin-top:7px;padding-top:7px;border-top:1px solid rgba(255,255,255,.06)}#tg-pantheon .sub{color:#78968b;font-size:8px}`;document.head.appendChild(s);
const box=document.createElement('div');box.id='tg-pantheon';box.innerHTML='<b>LIVING PANTHEON</b>';document.getElementById('wrap').appendChild(box);
function refreshPantheon(){if(typeof tgV7Mode!=='undefined'&&tgV7Mode!=='world'){box.style.display='none';return}box.style.display='block';if(typeof tgV9Pantheon==='function')tgV9Pantheon();let rows=(world.pantheon||[]).slice(0,4).map(d=>`<div class="god" style="color:hsl(${d.arch.hue} 80% 76%)">${d.arch.sigil} ${d.arch.name}<div class="sub">${d.arch.title}<br>mortal vessel · ${d.agent.n}</div></div>`).join('');box.innerHTML='<b>LIVING PANTHEON</b>'+ (rows||'<div class="sub" style="margin-top:7px">No figure has yet become mythic.</div>')}
function sky(){if(typeof tgV7Mode!=='undefined'&&tgV7Mode!=='world')return;let phase=(day%1),night=Math.max(0,Math.cos(phase*TAU));ctx.save();let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,`rgba(20,40,55,${.06+.12*night})`);g.addColorStop(1,'rgba(4,10,12,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<22;i++){let x=(i*211+performance.now()*.005)%Math.max(W,1),y=45+(i*59)%Math.max(80,H*.5);ctx.fillStyle=`rgba(220,246,232,${.02+.04*night})`;ctx.fillRect(x,y,1,1)}ctx.restore()}
function omenPulse(){if(!world.divineAttributions?.length)return;let r=world.divineAttributions[0];if(!r||r._seen)return;r._seen=true;let s=world.settlements.find(x=>x.n===r.settlement);let d=(world.pantheon||[]).find(x=>x.arch.name===r.deity);if(!s||!d)return;world.omens.unshift({s,d,t:0,dur:5,label:r.claim});world.omens=world.omens.slice(0,6)}
function drawOmens(dt){for(let i=world.omens.length-1;i>=0;i--){let o=world.omens[i];o.t+=dt;if(o.t>o.dur){world.omens.splice(i,1);continue}if(typeof tgV7Mode!=='undefined'&&tgV7Mode!=='world')continue;let p=typeof tgV9WorldPoint==='function'?tgV9WorldPoint(o.s):{x:0,y:0},q=o.t/o.dur,r=28+70*q;ctx.save();ctx.strokeStyle=`hsla(${o.d.arch.hue} 90% 76% / ${.55*(1-q)})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,r,0,TAU);ctx.stroke();ctx.fillStyle=`hsla(${o.d.arch.hue} 90% 76% / ${.65*(1-q)})`;ctx.font='9px ui-monospace';ctx.textAlign='center';ctx.fillText(o.label.toUpperCase(),p.x,p.y-r-8);ctx.restore()}}
let prev=performance.now();const baseDraw=draw;draw=function(){let now=performance.now(),dt=Math.min(.1,(now-prev)/1000);prev=now;baseDraw();sky();refreshPantheon();omenPulse();drawOmens(dt)};
log('✧ Cinematic layer online: the sky breathes, the living pantheon is inspectable, and divine claims now leave visible omens over settlements.');
})();