// Tiny Gods v0.7 — Construction in Progress
// Makes settlement growth visibly continuous with scaffolds, civic upgrades, and layered development.
world._tgV7Build=world._tgV7Build||new Map();
function tgV7BuildState(s){let st=world._tgV7Build.get(s.id);if(!st){st={lastPop:s.pop||0,lastTier:tgV7ProsperityTier(s),projects:[],phaseSeed:tgV7Seeded(s.id*211+13)};world._tgV7Build.set(s.id,st)}return st}
function tgV7QueueProject(s,kind){let st=tgV7BuildState(s);if(st.projects.some(p=>p.kind===kind))return;st.projects.push({kind,start:day,dur:kind==='civic'?rr(6,10):rr(3,7),seed:tgV7Seeded(s.id*337+st.projects.length*17+day)});if(s.history)s.history.unshift(`${kind==='civic'?'Civic works':'New construction'} began on day ${Math.floor(day)+1}`)}
function tgV7ConstructionUpdate(){for(const s of world.settlements){if(s.abandoned||s.pop<1)continue;let st=tgV7BuildState(s),tier=tgV7ProsperityTier(s);if(s.pop>=st.lastPop+3)tgV7QueueProject(s,'hut');if(tier>st.lastTier)tgV7QueueProject(s,'civic');st.lastPop=s.pop;st.lastTier=tier;st.projects=st.projects.filter(p=>day-p.start<p.dur+1)}}
const tgV7BuildBaseUpdate=update;update=function(dt){tgV7BuildBaseUpdate(dt);tgV7ConstructionUpdate()};
function tgV7ProjectProgress(p){return clamp((day-p.start)/Math.max(.001,p.dur),0,1)}
function tgV7DrawScaffold(s){let st=tgV7BuildState(s),p=st.projects.find(x=>x.kind==='hut');if(!p)return;let q=tgV7ProjectProgress(p),pp=tgV7Proj(165-40*p.seed,165+30*p.seed),w=42*pp.s,h=34*pp.s;ctx.save();ctx.strokeStyle='rgba(205,183,139,.55)';ctx.lineWidth=2*pp.s;ctx.setLineDash([5*pp.s,4*pp.s]);ctx.strokeRect(pp.x-w/2,pp.y-h*q,w,h*q);ctx.setLineDash([]);for(let i=0;i<3;i++){let xx=pp.x-w/2+i*w/2;ctx.beginPath();ctx.moveTo(xx,pp.y);ctx.lineTo(xx,pp.y-h*q);ctx.stroke()}ctx.strokeStyle='rgba(162,138,96,.4)';ctx.beginPath();ctx.moveTo(pp.x-w*.58,pp.y-h*q*.55);ctx.lineTo(pp.x+w*.58,pp.y-h*q*.55);ctx.stroke();ctx.fillStyle='rgba(238,220,177,.72)';ctx.font=`${8+3*pp.s}px ui-monospace`;ctx.fillText(q<.95?'BUILDING':'FINISHING',pp.x-24*pp.s,pp.y+17*pp.s);ctx.restore()}
function tgV7DrawCivicUpgrade(s){let st=tgV7BuildState(s),p=st.projects.find(x=>x.kind==='civic');if(!p)return;let q=tgV7ProjectProgress(p),pp=tgV7Proj(0,62);ctx.save();ctx.strokeStyle=`hsla(${s.hue} 70% 76% / ${.22+.25*q})`;ctx.lineWidth=2*pp.s;ctx.setLineDash([7*pp.s,5*pp.s]);ctx.beginPath();ctx.ellipse(pp.x,pp.y,90*pp.s,30*pp.s,0,0,TAU);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(226,215,188,.6)';ctx.font=`${9+3*pp.s}px ui-monospace`;ctx.fillText(q<.85?'CIVIC WORKS':'OPENING',pp.x-28*pp.s,pp.y-35*pp.s);for(let i=0;i<4;i++){let a=i/4*TAU+q*.6;ctx.fillStyle='rgba(150,128,91,.6)';ctx.fillRect(pp.x+Math.cos(a)*65*pp.s-3,pp.y+Math.sin(a)*16*pp.s-10*pp.s*q,6,10*pp.s*q)}ctx.restore()}
function tgV7LaterDevelopment(s){let tier=tgV7ProsperityTier(s);if(tier<2)return;let pp=tgV7Proj(-92,38);ctx.save();ctx.strokeStyle='rgba(205,198,177,.16)';ctx.lineWidth=1.4*pp.s;for(let i=0;i<tier+1;i++){let off=i*16*pp.s;ctx.strokeRect(pp.x-32*pp.s-off,pp.y-9*pp.s-off*.12,26*pp.s,18*pp.s)}ctx.restore()}
const tgV7BuildBaseClose=tgV7Close;tgV7Close=function(){tgV7BuildBaseClose();let s=tgV7Settlement;if(!s||s.abandoned)return;tgV7LaterDevelopment(s);tgV7DrawScaffold(s);tgV7DrawCivicUpgrade(s)};
log('⚒ Growth is now visible: settlements build, upgrade, and absorb old landmarks over time.');