// Tiny Gods v0.3 — Culture & Kin
// Injected into the terrarium script so it shares the simulation's lexical world.
const TG_CULTURES=['Ember Rite','Moss Covenant','Open Hand','Wayfarer Kin','Stone Memory','River Oath','Lantern Folk','Quiet Root','Sky Mark','Hearth Circle'];
const TG_SIGILS=['◇','△','○','✦','⌁','⊙','⋔','⋈','☼','⌂'];
world.splits=world.splits||0; world.pacts=world.pacts||0; world.feuds=world.feuds||0; world.trades=world.trades||0; world.caravans=world.caravans||[];
let tgSelectedSettlement=null;
function tgCulture(parent=null){if(parent){return{name:R()<.72?parent.name:TG_CULTURES[Math.floor(R()*TG_CULTURES.length)],sigil:R()<.82?parent.sigil:TG_SIGILS[Math.floor(R()*TG_SIGILS.length)],communal:clamp(parent.communal+rr(-.14,.14),0,1),bold:clamp(parent.bold+rr(-.14,.14),0,1),wandering:clamp(parent.wandering+rr(-.16,.16),0,1)}}return{name:TG_CULTURES[Math.floor(R()*TG_CULTURES.length)],sigil:TG_SIGILS[Math.floor(R()*TG_SIGILS.length)],communal:rr(.25,.9),bold:rr(.15,.85),wandering:rr(.15,.85)}}
function tgDecorate(s,parent=null){if(s.culture)return s;s.culture=tgCulture(parent?parent.culture:null);s.parent=parent||null;s.relations=new Map();s.foundedDay=Math.floor(day)+1;s.lastSplitDay=day;s.history=[];s.history.unshift(`Founded on day ${s.foundedDay}`);log(`◈ ${s.n} keeps ${s.culture.sigil} ${s.culture.name}: ${s.culture.communal>.62?'sharing':s.culture.bold>.62?'boldness':'wandering'} shapes the camp.`);return s}
function tgRel(a,b){return !a||!b||a===b?0:(a.relations?.get(b.id)??0)}
function tgSetRel(a,b,v){if(!a.relations)a.relations=new Map();if(!b.relations)b.relations=new Map();v=clamp(v,-1,1);a.relations.set(b.id,v);b.relations.set(a.id,v)}
function tgSimilarity(a,b){return 1-(Math.abs(a.culture.communal-b.culture.communal)+Math.abs(a.culture.bold-b.culture.bold)+Math.abs(a.culture.wandering-b.culture.wandering))/3}
function tgSite(s){for(let i=0;i<90;i++){let an=rr(0,TAU),d=rr(190,370),x=s.x+Math.cos(an)*d,y=s.y+Math.sin(an)*d;if(x>60&&x<world.w-60&&y>60&&y<world.h-60&&isLand(x,y)&&world.settlements.every(o=>o===s||o.abandoned||Math.hypot(o.x-x,o.y-y)>145))return{x,y}}return null}
function tgSplit(s){if(s.abandoned||s.pop<10||day-(s.lastSplitDay||0)<18)return;let pressure=s.pop/18+CFG.scarcity*.45+s.culture.wandering*.35;if(R()>.004*pressure)return;let site=tgSite(s);if(!site)return;let members=world.agents.filter(a=>a.alive&&a.home===s).sort((a,b)=>(b.curious+b.social*.2)-(a.curious+a.social*.2));let migrants=members.slice(0,Math.min(5,Math.max(3,Math.floor(s.pop*.28))));if(migrants.length<3)return;let child={id:world.settlements.length,n:name()+' '+(['Reach','Vale','Ford','Rest','Watch'][Math.floor(R()*5)]),x:site.x,y:site.y,pop:migrants.length,store:Math.min(.35,s.store*.22),age:0,hue:(s.hue+Math.floor(rr(-28,29))+360)%360,peak:migrants.length,abandoned:false};tgDecorate(child,s);s.store=Math.max(0,s.store-child.store);world.settlements.push(child);for(const a of migrants){a.home=child;addMemory(a,`Left ${s.n} to found ${child.n}`)}s.lastSplitDay=day;world.splits++;tgSetRel(s,child,.55);s.history.unshift(`${child.n} split away on day ${Math.floor(day)+1}`);child.history.unshift(`Split from ${s.n}`);world.caravans.push({kind:'migration',from:s,to:child,t:0,dur:rr(5,8),count:migrants.length});log(`⇢ ${child.n} split from ${s.n}; ${child.culture.sigil} ${child.culture.name} traveled with them.`)}
function tgDiplomacy(dt){let active=world.settlements.filter(s=>!s.abandoned&&s.pop>0&&s.culture);for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){let a=active[i],b=active[j],dist=Math.hypot(a.x-b.x,a.y-b.y);if(dist>620)continue;let old=tgRel(a,b),sim=tgSimilarity(a,b),kin=(a.parent===b||b.parent===a||a.parent&&a.parent===b.parent)?.18:0;let drift=((sim-.5)*.035+kin-CFG.scarcity*.018*(a.culture.bold+b.culture.bold))*dt,v=clamp(old+drift,-1,1);tgSetRel(a,b,v);if(old<.62&&v>=.62){world.pacts++;a.history.unshift(`Pact with ${b.n} on day ${Math.floor(day)+1}`);b.history.unshift(`Pact with ${a.n} on day ${Math.floor(day)+1}`);log(`⋈ ${a.n} and ${b.n} formed a pact between ${a.culture.name} and ${b.culture.name}.`)}if(old>-.58&&v<=-.58){world.feuds++;a.history.unshift(`Feud with ${b.n} on day ${Math.floor(day)+1}`);b.history.unshift(`Feud with ${a.n} on day ${Math.floor(day)+1}`);log(`⚔ ${a.n} and ${b.n} entered a feud over land and custom.`)}}}
function tgTrade(dt){let active=world.settlements.filter(s=>!s.abandoned&&s.pop>0&&s.culture);for(const a of active){if(a.store<.65)continue;let partners=active.filter(b=>b!==a&&tgRel(a,b)>.58&&b.store<a.store-.18&&Math.hypot(a.x-b.x,a.y-b.y)<650);if(!partners.length)continue;let b=partners[Math.floor(R()*partners.length)];if(world.caravans.some(c=>c.kind==='trade'&&c.from===a&&c.to===b))continue;if(R()<dt*.007*(.4+a.culture.communal)){let cargo=Math.min(.22,Math.max(.08,(a.store-b.store)*.28));a.store-=cargo;world.caravans.push({kind:'trade',from:a,to:b,t:0,dur:rr(6,10),cargo});log(`⇄ ${a.n} sent a trade caravan toward ${b.n}.`)}}}
function tgUpdateCaravans(dt){for(let i=world.caravans.length-1;i>=0;i--){let c=world.caravans[i];c.t+=dt;if(c.t<c.dur)continue;if(c.kind==='trade'&&!c.to.abandoned){c.to.store=clamp(c.to.store+c.cargo,0,2);world.trades++;c.from.history.unshift(`Traded with ${c.to.n} on day ${Math.floor(day)+1}`);c.to.history.unshift(`Received trade from ${c.from.n} on day ${Math.floor(day)+1}`);log(`⇄ Trade reached ${c.to.n} from ${c.from.n}.`)}world.caravans.splice(i,1)}}
const tgBaseUpdate=update;update=function(dt){tgBaseUpdate(dt);for(const s of world.settlements)tgDecorate(s,s.parent||null);for(const s of [...world.settlements])tgSplit(s);tgDiplomacy(dt);tgTrade(dt);tgUpdateCaravans(dt);for(const a of world.agents){if(!a.alive||!a.home?.culture)continue;let c=a.home.culture,k=Math.min(.0018*dt,1);a.social=lerp(a.social,c.communal,k);a.aggro=lerp(a.aggro,c.bold*.72,k);a.curious=lerp(a.curious,c.wandering,k)}};
function tgSettlementCard(s){let card=document.getElementById('agentcard');if(!s||s.abandoned){card.classList.remove('on');return}let rels=world.settlements.filter(o=>o!==s&&!o.abandoned&&Math.abs(tgRel(s,o))>.28).sort((a,b)=>Math.abs(tgRel(s,b))-Math.abs(tgRel(s,a))).slice(0,3);let parent=s.parent?`<div class="meta">Founded day ${s.foundedDay} · Daughter of ${s.parent.n}</div>`:`<div class="meta">Founded day ${s.foundedDay} · First generation settlement</div>`;let relationHtml=rels.length?rels.map(o=>`<div>${tgRel(s,o)>.58?'⋈ pact':tgRel(s,o)<-.58?'⚔ feud':'• relation'} · ${o.n}</div>`).join(''):'<div>No strong diplomatic ties yet.</div>';let history=(s.history||[]).slice(0,4).map(h=>`<div>• ${h}</div>`).join('');card.classList.add('on');card.innerHTML=`<div class="name" style="color:hsl(${s.hue} 90% 78%)">${s.culture.sigil} ${s.n}</div>${parent}<div class="thought"><b>${s.culture.name}</b><br>Population ${s.pop} · Peak ${s.peak||s.pop} · Stores ${Math.round((s.store||0)*100)}%</div><div class="thought">CUSTOMS<br>sharing ${Math.round(s.culture.communal*100)} · boldness ${Math.round(s.culture.bold*100)} · wandering ${Math.round(s.culture.wandering*100)}</div><div class="thought">DIPLOMACY<br>${relationHtml}</div><div class="thought">HISTORY<br>${history||'No major events recorded yet.'}</div>`}
canvas.addEventListener('click',e=>{if(typeof tgV7Mode!=='undefined'&&tgV7Mode==='close')return;const r=canvas.getBoundingClientRect(),sx=(e.clientX-r.left)*(W/r.width),sy=(e.clientY-r.top)*(H/r.height);const wx=(sx-W/2)/camera.z+world.w/2+camera.x,wy=(sy-H/2)/camera.z+world.h/2+camera.y;let best=null,bd=64*64;for(const s of world.settlements){if(s.abandoned||s.pop<1)continue;let dx=s.x-wx,dy=s.y-wy,d=dx*dx+dy*dy;if(d<bd){bd=d;best=s}}if(best){tgSelectedSettlement=best;selected=null;e.stopImmediatePropagation();tgSettlementCard(best)}else tgSelectedSettlement=null},true);
function tgOverlay(){ctx.save();ctx.translate(W/2,H/2);ctx.scale(camera.z,camera.z);ctx.translate(-world.w/2-camera.x,-world.h/2-camera.y);for(let i=0;i<world.settlements.length;i++)for(let j=i+1;j<world.settlements.length;j++){let a=world.settlements[i],b=world.settlements[j];if(a.abandoned||b.abandoned||a.pop<1||b.pop<1||!a.culture||!b.culture)continue;let rel=tgRel(a,b);if(Math.abs(rel)<.28)continue;ctx.save();ctx.setLineDash(rel>0?[8,7]:[2,8]);ctx.lineWidth=.8+Math.abs(rel)*1.4;ctx.strokeStyle=rel>0?`rgba(120,235,201,${.12+.2*Math.abs(rel)})`:`rgba(255,105,91,${.12+.22*Math.abs(rel)})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}for(const c of world.caravans){let p=clamp(c.t/c.dur,0,1),x=lerp(c.from.x,c.to.x,p),y=lerp(c.from.y,c.to.y,p);ctx.save();ctx.strokeStyle=c.kind==='trade'?'rgba(255,220,120,.38)':'rgba(170,220,255,.32)';ctx.setLineDash([4,7]);ctx.beginPath();ctx.moveTo(c.from.x,c.from.y);ctx.lineTo(c.to.x,c.to.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=c.kind==='trade'?'#ffe08a':'#b8ddff';ctx.shadowBlur=10;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(x,y,c.kind==='trade'?4:5,0,TAU);ctx.fill();ctx.restore()}for(const s of world.settlements){if(s.pop<1||!s.culture)continue;let rad=15+Math.sqrt(s.pop)*4;ctx.font='bold 13px ui-monospace';ctx.fillStyle=`hsla(${s.hue} 85% 78% / .9)`;ctx.fillText(s.culture.sigil,s.x-rad-2,s.y-rad-26);ctx.font='8px ui-monospace';ctx.fillStyle='rgba(205,231,219,.65)';ctx.fillText(s.culture.name,s.x-rad+14,s.y-rad-27);if(tgSelectedSettlement===s){ctx.strokeStyle='rgba(255,255,255,.82)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(s.x,s.y,rad+11,0,TAU);ctx.stroke()}}ctx.restore();let alive=world.agents.filter(a=>a.alive).length,camps=world.settlements.filter(s=>s.pop>0).length;document.getElementById('stats').innerHTML=[['DAY',Math.floor(day)+1],['ALIVE',alive],['CAMPS',camps],['SPLITS',world.splits],['PACTS',world.pacts],['TRADE',world.trades],['FEUDS',world.feuds]].map(([k,v])=>`<div class="stat glass"><small>${k}</small><strong>${v}</strong></div>`).join('');if(tgSelectedSettlement)tgSettlementCard(tgSelectedSettlement);else if(selected?.home?.culture){let meta=document.querySelector('#agentcard .meta');if(meta&&!meta.dataset.culture){meta.dataset.culture='1';meta.innerHTML+=`<br><span style="color:#b9f9df">${selected.home.culture.sigil} ${selected.home.culture.name}</span>`}}}
const tgBaseDraw=draw;draw=function(){tgBaseDraw();tgOverlay()};log('◈ Culture awakens: camps can inherit customs, split, trade, ally, feud, and remember their past.');