// Tiny Gods v0.6 — Dynasties & Echoes
// Legends now cast a faint inherited shadow: descendants can form named houses,
// carry prestige, and appear in a compact lineage ledger.
world.dynasties=world.dynasties||[];world._v6Seen=world._v6Seen||new Set();
const tgV6Style=document.createElement('style');tgV6Style.textContent=`#dynastyLedger{position:absolute;left:16px;top:138px;width:248px;padding:9px 11px;border-radius:14px;pointer-events:none}#dynastyLedger .ttl{font:800 8px ui-monospace,monospace;letter-spacing:.14em;color:#d8b8ff;margin-bottom:6px}.house{font:9px/1.35 ui-monospace,monospace;color:#9eb0aa;margin:5px 0}.house b{color:#f0dcff}.house em{font-style:normal;color:#cfe5da}.bloodmark{display:inline-block;width:6px;height:6px;border-radius:50%;margin-right:5px;box-shadow:0 0 8px currentColor}@media(max-width:900px){#dynastyLedger{display:none}}`;document.head.appendChild(tgV6Style);
const tgV6Ledger=document.createElement('div');tgV6Ledger.id='dynastyLedger';tgV6Ledger.className='glass';tgV6Ledger.innerHTML='<div class="ttl">HOUSES & BLOODLINES</div><div id="dynastyRows" class="house">No houses yet.</div>';document.getElementById('wrap').appendChild(tgV6Ledger);
function tgV6LegendForAgent(a){return world.legends.find(l=>l.agent===a)||null}
function tgV6Root(a,depth=0){if(!a||depth>5)return null;let self=tgV6LegendForAgent(a);if(self)return self;return tgV6Root(a.parentA,depth+1)||tgV6Root(a.parentB,depth+1)}
function tgV6HouseName(l){let base=l.name.replace(/[^A-Za-z]/g,'')||'Unnamed';let suffix=l.epithet==='the Founder'?'Founding':l.epithet==='the Far-Walker'?'Wayfarer':l.epithet==='the Keeper of Sparks'?'Spark':l.epithet==='the Many-Rooted'?'Root':l.epithet==='the Open Hand'?'Openhand':l.epithet==='the Iron Heart'?'Iron':'Memory';return `${base} ${suffix} House`}
function tgV6EnsureHouse(l){let h=world.dynasties.find(x=>x.legend===l);if(h)return h;h={legend:l,name:tgV6HouseName(l),hue:l.home?.hue??Math.floor(rr(20,340)),members:new Set(),living:0,prestige:clamp(.35+l.score*.09,0,1),founded:l.day};world.dynasties.unshift(h);world.dynasties=world.dynasties.slice(0,10);log(`♛ ${h.name} arose from the memory of ${l.name}.`);return h}
function tgV6Assign(a){if(!a||a._v6Assigned)return;a._v6Assigned=true;let root=tgV6Root(a);if(!root)return;let h=tgV6EnsureHouse(root);a.dynasty=h;let inheritance=a===root.agent?.5:.16;a.prestige=clamp((a.prestige||0)+h.prestige*inheritance,0,1);h.members.add(a.id);if(a.alive)h.living++;if(a!==root.agent&&a.alive){a.social=clamp(a.social+h.prestige*.018,0,1)}}
function tgV6Scan(){for(const a of world.agents)tgV6Assign(a);for(const h of world.dynasties){h.living=world.agents.filter(a=>a.alive&&a.dynasty===h).length}}
function tgV6SettlementPrestige(s){let m=world.agents.filter(a=>a.alive&&a.home===s&&a.dynasty);if(!m.length)return 0;return clamp(m.reduce((q,a)=>q+(a.prestige||0),0)/Math.max(2,m.length)*1.8,0,1)}
const tgV6BaseUpdate=update;update=function(dt){tgV6BaseUpdate(dt);tgV6Scan();for(const s of world.settlements){let p=tgV6SettlementPrestige(s);s.dynasticPrestige=p;if(p>.4&&s.culture){s.culture.communal=clamp(s.culture.communal+dt*.00002*p,0,1)}}};
const tgV6BaseCard=tgSettlementCard;tgSettlementCard=function(s){tgV6BaseCard(s);if(!s||s.abandoned)return;let card=document.getElementById('agentcard');let houses=[...new Set(world.agents.filter(a=>a.alive&&a.home===s&&a.dynasty).map(a=>a.dynasty))].sort((a,b)=>b.living-a.living);if(houses.length){card.innerHTML+=`<div class="thought">HOUSES<br>${houses.slice(0,3).map(h=>`<span style="color:hsl(${h.hue} 80% 78%)">♛ ${h.name}</span> · ${world.agents.filter(a=>a.alive&&a.home===s&&a.dynasty===h).length} here`).join('<br>')}</div>`}};
const tgV6BaseAgentCard=showCard;showCard=function(a){tgV6BaseAgentCard(a);if(!a?.dynasty)return;let card=document.getElementById('agentcard'),root=a.dynasty.legend;card.innerHTML+=`<div class="thought">LINEAGE<br><span style="color:hsl(${a.dynasty.hue} 80% 78%)">♛ ${a.dynasty.name}</span><br>Ancestor: ${root.name} ${root.epithet}<br>Prestige: ${Math.round((a.prestige||0)*100)}%</div>`};
function tgV6Draw(){ctx.save();tgV5WorldTransform();for(const a of world.agents){if(!a.alive||!a.dynasty||camera.z<.6)continue;let p=a.prestige||0;if(p<.08)continue;ctx.strokeStyle=`hsla(${a.dynasty.hue} 90% 75% / ${.08+p*.22})`;ctx.lineWidth=.8;ctx.beginPath();ctx.arc(a.x,a.y,7+p*5,0,TAU);ctx.stroke()}ctx.restore();let rows=document.getElementById('dynastyRows');if(rows){let hs=world.dynasties.filter(h=>h.living>0).sort((a,b)=>b.living-a.living||b.prestige-a.prestige);rows.innerHTML=hs.length?hs.slice(0,4).map(h=>`<div class="house"><span class="bloodmark" style="color:hsl(${h.hue} 80% 70%);background:currentColor"></span><b>${h.name}</b><br><em>${h.living} living</em> · founder D${h.founded}</div>`).join(''):'No houses yet.'}}
const tgV6BaseDraw=draw;draw=function(){tgV6BaseDraw();tgV6Draw()};
log('♛ Memory becomes inheritance: legendary bloodlines can now become houses.');