// Tiny Gods v0.7 — Settlement Identity
// Makes close-view architecture and civic space reflect live culture, prosperity and trade.
function tgV7ProsperityTier(s){let p=(typeof tgV5Prosperity==='function'?tgV5Prosperity(s):clamp((s.store||0)*.5+Math.min(s.pop,24)/48,0,1));return p>.72?3:p>.46?2:1}
function tgV7CivicType(s){let c=s.culture||{communal:.5,bold:.5,wandering:.5};if(c.communal>=c.bold&&c.communal>=c.wandering)return 'hearth';if(c.bold>=c.wandering)return 'court';return 'market'}
function tgV7Architecture(s){let c=s.culture||{communal:.5,bold:.5,wandering:.5};return c.bold>.64?'fortified':c.wandering>.64?'wayfarer':c.communal>.64?'clustered':'mixed'}
const tgV7IdentityBaseHut=tgV7Hut;
tgV7Hut=function(p,s,i){let tier=tgV7ProsperityTier(s),style=tgV7Architecture(s),w=(36+tier*3)*p.s,h=(29+tier*3)*p.s,x=p.x,y=p.y,roof=(style==='wayfarer'?14:style==='fortified'?13:19)*p.s;ctx.save();ctx.shadowBlur=12*p.s;ctx.shadowColor='rgba(0,0,0,.48)';let wallHue=style==='fortified'?30:style==='wayfarer'?36:25;let sat=style==='fortified'?12:24;let light=22+tier*3;ctx.fillStyle=`hsl(${wallHue} ${sat}% ${light}%)`;if(style==='wayfarer'){ctx.beginPath();ctx.moveTo(x-w*.55,y);ctx.lineTo(x-w*.42,y-h);ctx.lineTo(x+w*.42,y-h);ctx.lineTo(x+w*.55,y);ctx.closePath();ctx.fill()}else{ctx.fillRect(x-w/2,y-h,w,h)}ctx.fillStyle=style==='fortified'?'hsl(28 14% 20%)':`hsl(${18+tier*2} 32% ${18+tier*2}%)`;ctx.beginPath();if(style==='fortified'){ctx.moveTo(x-w*.56,y-h);ctx.lineTo(x-w*.42,y-h-roof);ctx.lineTo(x+w*.42,y-h-roof);ctx.lineTo(x+w*.56,y-h);ctx.closePath()}else{ctx.moveTo(x-w*.62,y-h);ctx.lineTo(x,y-h-roof);ctx.lineTo(x+w*.62,y-h);ctx.closePath()}ctx.fill();if(tier>=2){ctx.strokeStyle='rgba(225,209,177,.28)';ctx.lineWidth=1*p.s;ctx.strokeRect(x-w*.38,y-h*.72,w*.18,h*.18)}if(tier===3){ctx.fillStyle='rgba(255,193,104,.36)';ctx.fillRect(x+w*.17,y-h*.5,w*.14,h*.22)}else{ctx.fillStyle='rgba(255,183,94,.55)';ctx.fillRect(x-w*.08,y-h*.48,w*.16,h*.28)}if(style==='fortified'&&i%4===0){ctx.strokeStyle='rgba(190,190,176,.25)';ctx.lineWidth=3*p.s;ctx.beginPath();ctx.moveTo(x-w*.65,y);ctx.lineTo(x-w*.65,y-h*.72);ctx.stroke()}if(i===0&&s.culture){ctx.strokeStyle=`hsl(${s.hue} 80% 72%)`;ctx.lineWidth=2*p.s;ctx.beginPath();ctx.moveTo(x+w*.58,y-h-roof*.2);ctx.lineTo(x+w*.58,y-h-roof*2);ctx.stroke();ctx.fillStyle=`hsl(${s.hue} 75% 62%)`;ctx.beginPath();ctx.moveTo(x+w*.58,y-h-roof*1.9);ctx.lineTo(x+w*1.04,y-h-roof*1.55);ctx.lineTo(x+w*.58,y-h-roof*1.25);ctx.closePath();ctx.fill()}ctx.restore()};
function tgV7CivicSpace(s){let kind=tgV7CivicType(s),tier=tgV7ProsperityTier(s),p=tgV7Proj(0,60);ctx.save();if(kind==='hearth'){ctx.fillStyle='rgba(120,104,78,.18)';ctx.beginPath();ctx.ellipse(p.x,p.y,76*p.s,24*p.s,0,0,TAU);ctx.fill();for(let i=0;i<6+tier;i++){let a=i/(6+tier)*TAU;ctx.fillStyle='rgba(115,94,65,.7)';ctx.fillRect(p.x+Math.cos(a)*34*p.s-4,p.y+Math.sin(a)*11*p.s-2,8,4)}ctx.font=`${10+3*tier}px ui-monospace`;ctx.fillStyle='rgba(236,225,195,.7)';ctx.fillText('HEARTH CIRCLE',p.x-44,p.y+31*p.s)}else if(kind==='court'){ctx.strokeStyle='rgba(190,185,164,.28)';ctx.lineWidth=3*p.s;ctx.strokeRect(p.x-60*p.s,p.y-18*p.s,120*p.s,36*p.s);for(let i=-2;i<=2;i++){ctx.fillStyle='rgba(170,164,146,.35)';ctx.fillRect(p.x+i*24*p.s-2,p.y-28*p.s,4,28*p.s)}ctx.font=`${10+3*tier}px ui-monospace`;ctx.fillStyle='rgba(230,225,208,.65)';ctx.fillText('STONE COURT',p.x-40,p.y+31*p.s)}else{ctx.fillStyle='rgba(134,104,63,.16)';ctx.fillRect(p.x-70*p.s,p.y-14*p.s,140*p.s,28*p.s);for(let i=-2;i<=2;i++){let xx=p.x+i*26*p.s;ctx.fillStyle=`hsla(${(s.hue+i*18+360)%360} 55% 55% / .45)`;ctx.fillRect(xx-9*p.s,p.y-27*p.s,18*p.s,13*p.s)}ctx.font=`${10+3*tier}px ui-monospace`;ctx.fillStyle='rgba(238,219,184,.68)';ctx.fillText('WAY MARKET',p.x-38,p.y+31*p.s)}ctx.restore()}
function tgV7TradeArrival(s){let incoming=world.caravans.filter(c=>c.kind==='trade'&&c.to===s);for(let i=0;i<incoming.length;i++){let c=incoming[i],q=clamp(c.t/c.dur,0,1);if(q<.72)continue;let p=tgV7Proj(-55+i*48,115);ctx.save();ctx.fillStyle='rgba(129,94,52,.85)';ctx.fillRect(p.x-10*p.s,p.y-8*p.s,20*p.s,10*p.s);ctx.strokeStyle='#ffe08a';ctx.lineWidth=2*p.s;ctx.beginPath();ctx.moveTo(p.x-8*p.s,p.y-8*p.s);ctx.lineTo(p.x,p.y-18*p.s);ctx.lineTo(p.x+8*p.s,p.y-8*p.s);ctx.stroke();ctx.fillStyle='rgba(255,224,138,.8)';ctx.font=`${8+3*p.s}px ui-monospace`;ctx.fillText(q>.92?'UNLOADING':'ARRIVING',p.x-24*p.s,p.y+18*p.s);ctx.restore()}}
const tgV7IdentityBaseClose=tgV7Close;
tgV7Close=function(){let s=tgV7Settlement;if(!s||s.abandoned){tgV7Exit();return}tgV7Ground(s);tgV7Road();let layout=tgV7Layout(s);for(const h of layout){let p=tgV7Proj(h.x,h.y);tgV7Hut(p,s,h.i)}tgV7CivicSpace(s);tgV7Monument(s);tgV7Caravans(s);tgV7TradeArrival(s);tgV7Fire(s);tgV7Hits=tgV7People(s);tgV7Trees();tgV7Weather();let tier=tgV7ProsperityTier(s),arch=tgV7Architecture(s),civic=tgV7CivicType(s);ctx.fillStyle='rgba(235,255,246,.92)';ctx.font='800 12px ui-monospace';ctx.fillText(`${s.culture?.sigil||'⌂'} ${s.n}`,22,30);ctx.font='9px ui-monospace';ctx.fillStyle='rgba(210,232,224,.66)';ctx.fillText(`${s.culture?.name||'settlement'} · pop ${s.pop} · stores ${Math.round((s.store||0)*100)}%`,22,47);ctx.fillText(`${['','hamlet','village','prosperous town'][tier]} · ${arch} plan · ${civic} center`,22,62);if(s.founder)ctx.fillText(`founded by ${s.founder.n}`,22,77)};
log('⌂ Settlements now wear their culture: architecture, civic space, and prosperity are visible up close.');