// Tiny Gods v0.5 — Legends
// Tracks consequential lives and turns them into persistent cultural memory.
world.legends=world.legends||[];
for(const a of world.agents){a._v5x=a.x;a._v5y=a.y;a.travel=a.travel||0;a._v5alive=a.alive}
const tgV5LegendStyle=document.createElement('style');tgV5LegendStyle.textContent=`#legendHall{position:absolute;right:16px;top:138px;width:250px;padding:9px 11px;border-radius:14px;pointer-events:none}#legendHall .ttl{font:800 8px ui-monospace,monospace;letter-spacing:.14em;color:#f2d58d;margin-bottom:6px}.legend{font:9px/1.35 ui-monospace,monospace;color:#9eb0aa;margin:4px 0}.legend b{color:#fff1bd}.legend em{color:#cde8dc;font-style:normal}@media(max-width:900px){#legendHall{display:none}}`;document.head.appendChild(tgV5LegendStyle);
const tgV5LegendHall=document.createElement('div');tgV5LegendHall.id='legendHall';tgV5LegendHall.className='glass';tgV5LegendHall.innerHTML='<div class="ttl">HALL OF MEMORY</div><div id="legendRows" class="legend">No legends yet.</div>';document.getElementById('wrap').appendChild(tgV5LegendHall);
function tgV5Children(a){return world.agents.filter(c=>c.parentA===a||c.parentB===a).length}
function tgV5AssignFounders(){for(const s of world.settlements){if(s.founder||s.abandoned)continue;let m=world.agents.filter(a=>a.alive&&a.home===s);if(!m.length)continue;m.sort((a,b)=>(b.social+b.curious+b.age/100)-(a.social+a.curious+a.age/100));s.founder=m[0];s.founder.founded=(s.founder.founded||0)+1;s.history=s.history||[];s.history.unshift(`Founded by ${s.founder.n}`)}}
function tgV5Epithet(a){let kids=tgV5Children(a),f=a.friends?.size||0;if((a.founded||0)>0)return 'the Founder';if(a.travel>8500&&a.curious>.6)return 'the Far-Walker';if(a.knowledge>=3)return 'the Keeper of Sparks';if(kids>=5)return 'the Many-Rooted';if(f>=7&&a.social>.65)return 'the Open Hand';if(a.age>=80)return 'the Long-Lived';if(a.aggro>.72&&world.conflicts>5)return 'the Iron Heart';return 'the Remembered'}
function tgV5LegendScore(a){let kids=tgV5Children(a),f=a.friends?.size||0;return (a.founded||0)*3+Math.min(3,a.knowledge)*.9+Math.min(7,kids)*.45+Math.min(8,f)*.18+Math.min(2,a.travel/6500)+Math.max(0,a.age-55)/25}
function tgV5Remember(a){if(a._legendRecorded)return;a._legendRecorded=true;let score=tgV5LegendScore(a);if(score<3.2)return;let epithet=tgV5Epithet(a),home=a.home||null,legend={agent:a,name:a.n,epithet,age:Math.floor(a.age),day:Math.floor(day)+1,travel:Math.floor(a.travel||0),children:tgV5Children(a),knowledge:a.knowledge||0,home,score};world.legends.unshift(legend);world.legends=world.legends.slice(0,12);if(home){home.history=home.history||[];home.history.unshift(`${a.n} ${epithet} entered legend on day ${legend.day}`)}log(`★ ${a.n} ${epithet} passed into legend.`)}
function tgV5LifeTrack(){for(const a of world.agents){if(a._v5x==null){a._v5x=a.x;a._v5y=a.y;a._v5alive=a.alive;a.travel=0}if(a.alive){a.travel=(a.travel||0)+Math.hypot(a.x-a._v5x,a.y-a._v5y);a._v5x=a.x;a._v5y=a.y}if(a._v5alive&&!a.alive)tgV5Remember(a);a._v5alive=a.alive}}
const tgV5LegendBaseUpdate=update;update=function(dt){tgV5LegendBaseUpdate(dt);tgV5AssignFounders();tgV5LifeTrack()};
const tgV5LegendBaseCard=tgSettlementCard;tgSettlementCard=function(s){tgV5LegendBaseCard(s);if(!s||s.abandoned)return;let card=document.getElementById('agentcard');if(s.founder){let l=world.legends.find(x=>x.agent===s.founder),title=l?`${s.founder.n} ${l.epithet}`:s.founder.n;card.innerHTML+=`<div class="thought">FOUNDER<br><span style="color:#fff1bd">★ ${title}</span></div>`}if(s.monument){let d=s.monument.dedication||s.founder;card.innerHTML+=`<div class="thought">MONUMENT<br>${s.monument.type} · D${s.monument.day}${d?`<br>Dedicated to ${d.n}`:''}</div>`}}
function tgV5LegendRender(){let rows=document.getElementById('legendRows');if(!rows)return;if(!world.legends.length){rows.innerHTML='No legends yet.';return}rows.innerHTML=world.legends.slice(0,3).map(l=>`<div class="legend"><b>★ ${l.name}</b> <em>${l.epithet}</em><br>D${l.day} · age ${l.age} · ${l.children} children${l.home?' · '+l.home.n:''}</div>`).join('')}
const tgV5LegendBaseDraw=draw;draw=function(){tgV5LegendBaseDraw();tgV5LegendRender()};
log('★ Lives can now outlast bodies: consequential people may become legends.');