// Tiny Gods v0.8 — Myth Transmission
// Stories can move through kinship and trade, preserving a common root while wording drifts.
world._tgV8Shared=world._tgV8Shared||new Set();
function tgV8StorySignature(m){return `${m.kind}:${m.source?.name||m.source?.label||m.source?.type||m.day}`}
function tgV8CloneMyth(m,to,mode){let sig=tgV8StorySignature(m),key=`${m.settlement.id}>${to.id}:${sig}`;if(world._tgV8Shared.has(key))return;world._tgV8Shared.add(key);to.myths=to.myths||[];if(to.myths.some(x=>tgV8StorySignature(x)===sig))return;let c={...m,settlement:to,day:Math.floor(day)+1,weight:m.weight*.72,tone:mode==='kin'?'kept':'heard',drift:(m.drift||0)+1};c.text=tgV8Text(c);if(mode==='trade')c.text=c.text.replace(`${to.n} heard`,`${to.n} heard from travelers`).replace(`${to.n} keeps`,`${to.n} repeats`);else c.text=c.text.replace(`${to.n} kept`,`${to.n} says its kin remembered`);to.myths.unshift(c);to.myths=to.myths.slice(0,8);world.myths.unshift(c);world.myths=world.myths.slice(0,40);if(to.history)to.history.unshift(`A story from ${m.settlement.n} entered local memory on day ${Math.floor(day)+1}`)}
function tgV8Transmit(){let active=world.settlements.filter(s=>!s.abandoned&&s.pop>0&&s.myths?.length);for(const a of active){for(const b of active){if(a===b)continue;let kin=a.parent===b||b.parent===a||(a.parent&&a.parent===b.parent),trade=tgRel(a,b)>.58;if(!kin&&!trade)continue;if(tgV7Seeded(Math.floor(day)*97+a.id*17+b.id*31)>.006*(kin?1.6:1))continue;let m=a.myths[Math.floor(tgV7Seeded(day*13+a.id*41)*Math.min(3,a.myths.length))];if(m)tgV8CloneMyth(m,b,kin?'kin':'trade')}}}
const tgV8TransmissionBaseUpdate=update;update=function(dt){tgV8TransmissionBaseUpdate(dt);tgV8Transmit()};
function tgV8SharedMemoryOverlay(){if(tgV7Mode!=='close'||!tgV7Settlement)return;let s=tgV7Settlement,borrowed=(s.myths||[]).filter(m=>m.settlement===s&&m.day>=(s.foundedDay||0)&&m.drift>0);if(!borrowed.length)return;ctx.save();ctx.fillStyle='rgba(198,220,255,.55)';ctx.font='8px ui-monospace';ctx.fillText(`shared stories · ${borrowed.length}`,22,H-112);ctx.restore()}
const tgV8TransmissionBaseClose=tgV7Close;tgV7Close=function(){tgV8TransmissionBaseClose();tgV8SharedMemoryOverlay()};
log('⌁ Stories travel too: kin and trade can carry myths between settlements, changing them slightly along the way.');