// Tiny Gods v0.9 — Overdrive
// Final spectacle pass: miniature world settlements, atmosphere, village districts, inspect tabs, and mythic attribution.
(function(){
world.divineAttributions=world.divineAttributions||[];
function wp(x,y){return{x:(x-world.w/2-camera.x)*camera.z+W/2,y:(y-world.h/2-camera.y)*camera.z+H/2}}
function worldVillage(s){let p=wp(s.x,s.y),z=clamp(camera.z,.55,1.7);if(p.x<-100||p.x>W+100||p.y<-100||p.y>H+100)return;ctx.save();ctx.translate(p.x,p.y);let n=Math.min(9,2+Math.floor(Math.sqrt(s.pop||1)*1.5));for(let i=0;i<n;i++){let a=i*2.399+(s.id||0),r=9+Math.sqrt(i)*8,x=Math.cos(a)*r*z,y=Math.sin(a)*r*.55*z,w=7*z,h=5*z;ctx.fillStyle=`hsl(${28+(i%3)*5} 28% ${22+Math.min(10,(s.store||0)*9)}%)`;ctx.fillRect(x-w/2,y-h,w,h);ctx.fillStyle='hsl(20 35% 16%)';ctx.beginPath();ctx.moveTo(x-w*.7,y-h);ctx.lineTo(x,y-h-5*z);ctx.lineTo(x+w*.7,y-h);ctx.closePath();ctx.fill();if((day%1)>.55){ctx.fillStyle='rgba(255,185,88,.7)';ctx.fillRect(x-1*z,y-h*.65,2*z,2*z)}}ctx.strokeStyle=`hsla(${s.hue} 75% 70% / .65)`;ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(0,-12*z);ctx.lineTo(0,-31*z);ctx.stroke();ctx.fillStyle=`hsl(${s.hue} 75% 58%)`;ctx.beginPath();ctx.moveTo(0,-30*z);ctx.lineTo(13*z,-25*z);ctx.lineTo(0,-20*z);ctx.closePath();ctx.fill();for(let k=0;k<Math.min(3,Math.ceil((s.pop||1)/8));k++){let t=(performance.now()*.00008+k*.23+(s.id||0)*.1)%1;ctx.fillStyle=`rgba(190,205,195,${.16*(1-t)})`;ctx.beginPath();ctx.arc((k-1)*7*z+Math.sin(t*7)*3,-30*z-t*25*z,4+t*8,0,TAU);ctx.fill()}ctx.restore()}
function worldAtmosphere(){if(typeof tgV7Mode!=='undefined'&&tgV7Mode!=='world')return;ctx.save();let t=performance.now()*.00005;for(let i=0;i<32;i++){let x=(i*137+CFG.seed*3)%Math.max(W,1),y=(i*83+Math.sin(t*TAU+i)*45+H)%Math.max(H,1);ctx.fillStyle=`rgba(172,244,199,${.025+(i%5)*.008})`;ctx.beginPath();ctx.arc(x,y,1+(i%3),0,TAU);ctx.fill()}ctx.restore();for(const s of world.settlements)if(!s.abandoned&&s.pop>0)worldVillage(s)}
const bd=draw;draw=function(){bd();worldAtmosphere()};
function divineMemory(){if(!world.pantheon?.length||Math.floor(day)%7!==0||world._tgDivineDay===Math.floor(day))return;world._tgDivineDay=Math.floor(day);let d=world.pantheon[Math.floor((day+CFG.seed)%world.pantheon.length)],a=d.agent;if(!a?.home)return;let truths=[];if(a.knowledge>=2)truths.push('shared difficult knowledge');if(a.social>.72)truths.push('bound neighbors together');if(a.curious>.75)truths.push('walked beyond familiar roads');if(a.carry>.25)truths.push('returned carrying food');if(!truths.length)return;let truth=truths[Math.floor(day)%truths.length],claim=d.arch.domain==='light'?'blessed the season':d.arch.domain==='root'?'woke the green earth':d.arch.domain==='memory'?'sent a remembered dream':d.arch.domain==='spark'?'kindled a turning':d.arch.domain==='road'?'opened the road':d.arch.domain==='river'?'guided the flowing paths':'guarded the hearth';let rec={day:Math.floor(day)+1,deity:d.arch.name,agent:a.n,settlement:a.home.n,truth,claim};world.divineAttributions.unshift(rec);world.divineAttributions=world.divineAttributions.slice(0,16);log(`☼ ${a.home.n} says ${d.arch.name} ${claim}.`);a.home.history?.unshift(`People said ${d.arch.name} ${claim} on day ${rec.day}`)}
const bu=update;update=function(dt){bu(dt);divineMemory()};
function closeDetails(){if(typeof tgV7Mode==='undefined'||tgV7Mode!=='close'||!tgV7Settlement)return;let s=tgV7Settlement;ctx.save();let garden=tgV7Proj(155,112);ctx.strokeStyle='rgba(156,201,118,.5)';ctx.lineWidth=1;for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(garden.x-25,garden.y+i*5);ctx.lineTo(garden.x+25,garden.y+i*5);ctx.stroke()}for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#8fc56d':'#c8b35e';ctx.beginPath();ctx.arc(garden.x-22+i*5,garden.y-8+(i%3)*6,2,0,TAU);ctx.fill()}let sign=tgV7Proj(-145,95);ctx.fillStyle='rgba(80,55,32,.9)';ctx.fillRect(sign.x-2,sign.y-16,4,22);ctx.fillRect(sign.x-18,sign.y-17,36,12);ctx.fillStyle='rgba(239,221,180,.72)';ctx.font='7px ui-monospace';ctx.textAlign='center';ctx.fillText(s.culture?.sigil||'⌂',sign.x,sign.y-9);ctx.restore()}
const bc=tgV7Close;tgV7Close=function(){bc();closeDetails()};
const style=document.createElement('style');style.textContent=`#tg-village-tabs{position:absolute;left:50%;bottom:17px;transform:translateX(-50%);z-index:92;display:none;gap:5px;padding:5px;border-radius:13px;background:rgba(4,11,15,.82);border:1px solid rgba(255,255,255,.1);backdrop-filter:blur(12px)}#tg-village-tabs button{border:0;background:transparent;color:#9fb9ae;padding:7px 10px;border-radius:9px;font:800 8px ui-monospace;cursor:pointer}#tg-village-tabs button:hover,#tg-village-tabs button.on{background:rgba(124,248,199,.12);color:#dcfff0}#tg-village-panel{position:absolute;left:18px;bottom:72px;z-index:91;display:none;width:300px;max-height:180px;overflow:auto;padding:10px 12px;border-radius:12px;background:rgba(4,11,15,.86);border:1px solid rgba(255,255,255,.09);font:9px/1.45 ui-monospace;color:#cfe5da;backdrop-filter:blur(12px)}`;document.head.appendChild(style);
let tabs=document.createElement('div');tabs.id='tg-village-tabs';tabs.innerHTML='<button data-t="people">PEOPLE</button><button data-t="buildings">BUILDINGS</button><button data-t="stories">STORIES</button><button data-t="rituals">RITUALS</button><button data-t="trade">TRADE</button>';document.getElementById('wrap').appendChild(tabs);let panel=document.createElement('div');panel.id='tg-village-panel';document.getElementById('wrap').appendChild(panel);
function tabText(k){let s=tgV7Settlement;if(!s)return'';if(k==='people'){let ms=world.agents.filter(a=>a.alive&&a.home===s).slice(0,8);return `<b>PEOPLE OF ${s.n.toUpperCase()}</b><br>${ms.map(a=>`${a.n} · ${typeof tgV7ActivityLabel==='function'?tgV7ActivityLabel(tgV7Role(a,s)):'resident'}${a.dynasty?' · '+a.dynasty.name:''}`).join('<br>')||'No residents.'}`}if(k==='buildings')return `<b>BUILT WORLD</b><br>${typeof tgV7Architecture==='function'?tgV7Architecture(s):'mixed'} plan · ${typeof tgV7CivicType==='function'?tgV7CivicType(s):'hearth'} center<br>Population peak ${s.peak||s.pop}${s.monument?`<br>Monument · ${s.monument.type}`:''}${s.construction?.projects?.length?`<br>Active works · ${s.construction.projects.length}`:''}`;if(k==='stories')return `<b>STORIES & MEMORY</b><br>${(s.myths||[]).slice(0,4).map(m=>'◌ '+m.text).join('<br><br>')||'No stories have taken hold yet.'}`;if(k==='rituals')return `<b>RITUAL LIFE</b><br>${s.activeEvent?'Current · '+(s.activeEvent.label||s.activeEvent.kind):'No gathering at this moment.'}<br>${(s.history||[]).filter(x=>/feast|funeral|gather|dedicat|ritual/i.test(x)).slice(0,4).join('<br>')||'Ritual history is still young.'}`;let cs=world.caravans.filter(c=>c.from===s||c.to===s);return `<b>TRADE & ROADS</b><br>Stores ${Math.round((s.store||0)*100)}% · active caravans ${cs.length}<br>${world.settlements.filter(o=>o!==s&&!o.abandoned&&typeof tgRel==='function'&&tgRel(s,o)>.58).slice(0,4).map(o=>'⇄ '+o.n).join('<br>')||'No strong trade partners yet.'}`}
for(const b of tabs.querySelectorAll('button'))b.onclick=()=>{for(const x of tabs.querySelectorAll('button'))x.classList.remove('on');b.classList.add('on');panel.innerHTML=tabText(b.dataset.t);panel.style.display='block'};
function tabVisibility(){let close=typeof tgV7Mode!=='undefined'&&tgV7Mode==='close';tabs.style.display=close?'flex':'none';if(!close)panel.style.display='none'}
const oldDraw=draw;draw=function(){oldDraw();tabVisibility()};
log('✦ Overdrive engaged: villages gain miniature skylines, atmosphere, districts, inspect tabs, and cultures can mythologize the deeds of living gods.');
})();