// Tiny Gods v0.9 — The Pantheon
// Gives wandering high-impact agents mythic visual identities and upgrades people from dots to tiny figures.
world.pantheon=world.pantheon||[];
const TG_DIVINE=[
 {name:'Nyr',title:'Keeper of Roots',sigil:'♧',hue:145,domain:'root'},
 {name:'Solenn',title:'Wanderer of Light',sigil:'☼',hue:42,domain:'light'},
 {name:'Veyla',title:'Dreams & Memory',sigil:'☾',hue:276,domain:'memory'},
 {name:'Thal',title:'Rivers in Motion',sigil:'≋',hue:198,domain:'river'},
 {name:'Korr',title:'Spark & Change',sigil:'♨',hue:18,domain:'spark'},
 {name:'Aevra',title:'Watcher of Roads',sigil:'⌁',hue:188,domain:'road'},
 {name:'Mora',title:'Hearth & Kin',sigil:'⌂',hue:8,domain:'hearth'}
];
function tgV9DivineScore(a){if(!a||!a.alive)return 0;return (a.knowledge||0)*.12+(a.curious||0)*.28+(a.social||0)*.25+(a.friends?.size||0)*.035+(a.generation||0)*.025+(a.legend?1:.0)+(a.dynasty?.prestige||0)*.45}
function tgV9Archetype(a){let x=(a.id*17+CFG.seed)%TG_DIVINE.length;if(a.knowledge>=2)x=2;else if(a.curious>.78)x=5;else if(a.social>.76)x=6;else if(a.aggro>.68)x=4;return TG_DIVINE[x]}
function tgV9Pantheon(){let candidates=world.agents.filter(a=>a.alive&&tgV9DivineScore(a)>.48).sort((a,b)=>tgV9DivineScore(b)-tgV9DivineScore(a)).slice(0,5);world.pantheon=candidates.map(a=>({agent:a,arch:tgV9Archetype(a),score:tgV9DivineScore(a)}));}
function tgV9WorldPoint(a){return{x:(a.x-world.w/2-camera.x)*camera.z+W/2,y:(a.y-world.h/2-camera.y)*camera.z+H/2}}
function tgV9DrawDeity(d,i){let a=d.agent,p=tgV9WorldPoint(a),ar=d.arch;if(p.x<-90||p.x>W+90||p.y<-100||p.y>H+100)return;let pulse=.5+.5*Math.sin(performance.now()*.002+a.id),r=14+6*pulse;ctx.save();ctx.translate(p.x,p.y-24);ctx.shadowBlur=24;ctx.shadowColor=`hsla(${ar.hue} 90% 68% / .85)`;let g=ctx.createRadialGradient(0,0,2,0,0,r*2.4);g.addColorStop(0,`hsla(${ar.hue} 95% 78% / .55)`);g.addColorStop(1,`hsla(${ar.hue} 90% 55% / 0)`);ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r*2.4,0,TAU);ctx.fill();ctx.strokeStyle=`hsla(${ar.hue} 90% 80% / .72)`;ctx.lineWidth=1.3;ctx.beginPath();ctx.arc(0,0,r,0,TAU);ctx.stroke();ctx.fillStyle=`hsl(${ar.hue} 85% 76%)`;ctx.font='bold 16px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(ar.sigil,0,0);ctx.restore();ctx.save();let labelX=p.x+18,labelY=p.y-48;ctx.fillStyle='rgba(4,10,15,.84)';ctx.strokeStyle=`hsla(${ar.hue} 80% 70% / .4)`;ctx.lineWidth=1;let tw=Math.max(108,ctx.measureText(ar.title).width+28);ctx.beginPath();ctx.roundRect(labelX,labelY,tw,38,9);ctx.fill();ctx.stroke();ctx.fillStyle='#f1fff8';ctx.font='800 10px ui-monospace';ctx.textAlign='left';ctx.fillText(ar.name,labelX+10,labelY+15);ctx.fillStyle=`hsl(${ar.hue} 80% 75%)`;ctx.font='8px ui-monospace';ctx.fillText(ar.title,labelX+10,labelY+28);ctx.restore()}
function tgV9DrawWorldPantheon(){if(typeof tgV7Mode!=='undefined'&&tgV7Mode!=='world')return;tgV9Pantheon();for(let i=0;i<world.pantheon.length;i++)tgV9DrawDeity(world.pantheon[i],i)}
const tgV9BaseDraw=draw;draw=function(){tgV9BaseDraw();tgV9DrawWorldPantheon()};
// Replace close-view people with tiny readable humanoids while preserving role behavior and hit testing.
function tgV9PersonFigure(a,role,p,hover){let col=typeof tgV7RoleColor==='function'?tgV7RoleColor(role,a):(a.dynasty?`hsl(${a.dynasty.hue} 78% 74%)`:'#d9eee5'),s=p.s;ctx.save();ctx.shadowBlur=hover?12:3;ctx.shadowColor=col;ctx.fillStyle='rgba(238,205,165,.95)';ctx.beginPath();ctx.arc(p.x,p.y-12*s,(hover?4.2:3.5)*s,0,TAU);ctx.fill();ctx.fillStyle=col;ctx.beginPath();ctx.roundRect(p.x-4*s,p.y-8*s,8*s,12*s,2*s);ctx.fill();ctx.strokeStyle='rgba(235,244,239,.78)';ctx.lineWidth=1.4*s;ctx.beginPath();ctx.moveTo(p.x-2*s,p.y+3*s);ctx.lineTo(p.x-4*s,p.y+10*s);ctx.moveTo(p.x+2*s,p.y+3*s);ctx.lineTo(p.x+4*s,p.y+10*s);ctx.moveTo(p.x-4*s,p.y-4*s);ctx.lineTo(p.x-8*s,p.y+1*s);ctx.moveTo(p.x+4*s,p.y-4*s);ctx.lineTo(p.x+8*s,p.y+1*s);ctx.stroke();if(a.dynasty){ctx.fillStyle=`hsl(${a.dynasty.hue} 90% 70%)`;ctx.fillRect(p.x-4*s,p.y-7*s,8*s,2*s)}ctx.restore()}
function tgV7People(s){let members=world.agents.filter(a=>a.alive&&a.home===s).slice(0,Math.min(24,s.pop)),hits=[],now=day*.14;for(let i=0;i<members.length;i++){let a=members[i],role=typeof tgV7Role==='function'?tgV7Role(a,s):'resident',target=typeof tgV7RoleTarget==='function'?tgV7RoleTarget(role,s,i):{x:Math.sin(i)*110,y:110+Math.cos(i)*90},phase=(now+i*.173)%1,drift=role==='traveler'?55:role==='resident'?34:18,x=target.x+Math.sin((phase+i)*TAU)*drift,y=target.y+Math.cos((phase*.8+i)*TAU)*(role==='resident'?58:18),p=tgV7Proj(x,y);hits.push({a,x:p.x,y:p.y,r:13*p.s,role});tgV9PersonFigure(a,role,p,tgV7Hover===a);if(typeof tgV7DrawRoleProp==='function')tgV7DrawRoleProp(role,p,i);if(tgV7Hover===a){ctx.save();ctx.font='9px ui-monospace';ctx.fillStyle='rgba(247,255,251,.95)';ctx.fillText(`${a.n} · ${typeof tgV7ActivityLabel==='function'?tgV7ActivityLabel(role):'RESIDENT'}`,p.x+10*p.s,p.y-15*p.s);ctx.restore()}}return hits}
log('☼ The Pantheon stirs: exceptional wanderers now appear as mythic presences, while village people gain tiny bodies, clothing, and house marks.');