// Tiny Gods v0.7 — Rituals & Local Events
// Brief settlement events gather residents, enter local history, and create street-level moments.
world.rituals=world.rituals||[];
function tgV7MaybeRitual(s){if(s.abandoned||s.pop<4)return;if(world.rituals.some(r=>r.s===s))return;let chance=.0007+Math.min(.0015,s.pop*.00003);if(R()>chance)return;let kinds=[];if(world.caravans.some(c=>c.kind==='trade'&&c.to===s))kinds.push('market');if((s.monument||s.founder)&&R()<.7)kinds.push('dedication');if((s.culture?.communal||0)>.58)kinds.push('feast');if((s.culture?.bold||0)>.55)kinds.push('dispute');if(world.legends.some(l=>l.home===s&&day-l.day<12))kinds.push('funeral');if(!kinds.length)kinds=['gathering'];let kind=kinds[Math.floor(R()*kinds.length)],dur=rr(2.5,5.5);world.rituals.push({s,kind,start:day,dur});let text=kind==='market'?'A market day drew the settlement together.':kind==='dedication'?'A public dedication gathered around an old landmark.':kind==='feast'?'A communal feast filled the civic center.':kind==='dispute'?'A public dispute drew a tense crowd.':kind==='funeral'?'A funeral rite gathered kin and neighbors.':'A seasonal gathering formed in the civic center.';s.history=s.history||[];s.history.unshift(`${text.replace(/\.$/,'')} on day ${Math.floor(day)+1}`);log(`${kind==='dispute'?'⚖':kind==='funeral'?'✦':kind==='market'?'⇄':'☼'} ${s.n}: ${text}`)}
function tgV7RitualUpdate(dt){for(const s of world.settlements)tgV7MaybeRitual(s);for(let i=world.rituals.length-1;i>=0;i--){let r=world.rituals[i];if(day-r.start>r.dur)world.rituals.splice(i,1)}}
const tgV7RitualBaseUpdate=update;update=function(dt){tgV7RitualBaseUpdate(dt);tgV7RitualUpdate(dt)};
function tgV7RitualFor(s){return world.rituals.find(r=>r.s===s)||null}
function tgV7RitualDraw(s){let r=tgV7RitualFor(s);if(!r)return;let p=tgV7Proj(0,62),q=clamp((day-r.start)/r.dur,0,1),pulse=.5+.5*Math.sin(performance.now()*.01);ctx.save();ctx.strokeStyle=r.kind==='dispute'?'rgba(255,135,110,.45)':r.kind==='funeral'?'rgba(210,190,255,.45)':r.kind==='market'?'rgba(255,224,138,.45)':'rgba(140,240,195,.4)';ctx.lineWidth=2;ctx.setLineDash([4,5]);ctx.beginPath();ctx.ellipse(p.x,p.y,70+10*pulse,24+4*pulse,0,0,TAU);ctx.stroke();ctx.setLineDash([]);ctx.font='800 9px ui-monospace';ctx.fillStyle='rgba(245,255,250,.85)';ctx.fillText((r.kind==='market'?'MARKET DAY':r.kind==='dedication'?'DEDICATION':r.kind==='feast'?'COMMUNAL FEAST':r.kind==='dispute'?'PUBLIC DISPUTE':r.kind==='funeral'?'FUNERAL RITE':'SEASONAL GATHERING'),p.x-48,p.y-34);for(let i=0;i<8;i++){let a=i/8*TAU+pulse*.1,pp=tgV7Proj(Math.cos(a)*54,62+Math.sin(a)*18);ctx.fillStyle='rgba(230,245,238,.72)';ctx.beginPath();ctx.arc(pp.x,pp.y,2.5,0,TAU);ctx.fill()}ctx.restore()}
const tgV7RitualBaseClose=tgV7Close;tgV7Close=function(){tgV7RitualBaseClose();let s=tgV7Settlement;if(s&&!s.abandoned)tgV7RitualDraw(s)};
log('☼ Settlements now gather for markets, feasts, disputes, dedications, funerals, and seasonal rites.');