// Tiny Gods v0.7 — Under the Glass
// Close 2.5D settlement view derived from live simulation state.
let tgV7Mode='world',tgV7Settlement=null,tgV7Fade=0,tgV7Hover=null;
const tgV7Style=document.createElement('style');tgV7Style.textContent=`#underGlassHud{position:absolute;left:50%;bottom:18px;transform:translateX(-50%);display:flex;gap:8px;align-items:center;z-index:20}#underGlassHud button{border:1px solid rgba(255,255,255,.16);background:rgba(8,14,18,.78);color:#eafff6;border-radius:999px;padding:8px 12px;font:800 9px ui-monospace,monospace;letter-spacing:.1em;cursor:pointer;backdrop-filter:blur(8px)}#underGlassHud .place{font:800 9px ui-monospace,monospace;color:#c8ffea;letter-spacing:.12em}#underGlassHint{position:absolute;left:50%;bottom:58px;transform:translateX(-50%);font:700 8px ui-monospace,monospace;color:rgba(220,244,235,.6);letter-spacing:.1em;pointer-events:none}body.tg-close #stats,body.tg-close #historyStrip,body.tg-close #legendHall,body.tg-close #dynastyLedger{opacity:.12;pointer-events:none}body.tg-close #agentcard{z-index:30}`;document.head.appendChild(tgV7Style);
const tgV7Hud=document.createElement('div');tgV7Hud.id='underGlassHud';tgV7Hud.className='glass';tgV7Hud.style.display='none';tgV7Hud.innerHTML='<span class="place" id="underGlassPlace"></span><button id="underGlassExit">↑ RETURN TO WORLD</button>';document.getElementById('wrap').appendChild(tgV7Hud);
const tgV7Hint=document.createElement('div');tgV7Hint.id='underGlassHint';tgV7Hint.textContent='DOUBLE-CLICK A SETTLEMENT TO ENTER';document.getElementById('wrap').appendChild(tgV7Hint);
document.getElementById('underGlassExit').onclick=()=>tgV7Exit();
function tgV7Enter(s){if(!s||s.abandoned||s.pop<1)return;tgV7Settlement=s;tgV7Mode='close';tgV7Fade=1;document.body.classList.add('tg-close');tgV7Hud.style.display='flex';document.getElementById('underGlassPlace').textContent=`${s.culture?.sigil||'⌂'} ${s.n.toUpperCase()}`;tgV7Hint.style.display='none';log(`⌂ You descended into ${s.n}.`)}
function tgV7Exit(){tgV7Mode='world';tgV7Fade=1;document.body.classList.remove('tg-close');tgV7Hud.style.display='none';tgV7Hint.style.display='';tgV7Settlement=null;tgV7Hover=null;document.getElementById('agentcard').classList.remove('on')}
canvas.addEventListener('dblclick',e=>{if(tgV7Mode==='close')return;const r=canvas.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top,wx=(sx-W/2)/camera.z+world.w/2+camera.x,wy=(sy-H/2)/camera.z+world.h/2+camera.y;let best=null,bd=55*55;for(const s of world.settlements){if(s.abandoned||s.pop<1)continue;let d=(s.x-wx)**2+(s.y-wy)**2;if(d<bd){bd=d;best=s}}if(best){e.preventDefault();e.stopImmediatePropagation();tgV7Enter(best)}},true);
function tgV7Seeded(n){let x=Math.sin(n*12.9898+CFG.seed*.0001)*43758.5453;return x-Math.floor(x)}
function tgV7Layout(s){let count=Math.max(5,Math.min(22,Math.ceil(s.pop/1.9))),items=[];for(let i=0;i<count;i++){let ring=Math.floor(Math.sqrt(i))+1,ang=tgV7Seeded(i+s.id*31)*TAU,rrr=70+ring*38+tgV7Seeded(i*7+s.id)*22;items.push({x:Math.cos(ang)*rrr,y:Math.sin(ang)*rrr*.48,z:tgV7Seeded(i*13+s.id),i})}return items.sort((a,b)=>a.y-b.y)}
function tgV7Proj(x,y){let horizon=H*.29,depth=(y+260)/520,scale=.50+depth*.86;return{x:W/2+x*scale,y:horizon+depth*(H*.61),s:scale,d:depth}}
function tgV7Ground(s){let g=ctx.createLinearGradient(0,H*.22,0,H);g.addColorStop(0,'#31413a');g.addColorStop(.5,'#1c2823');g.addColorStop(1,'#0b100e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);let glow=ctx.createRadialGradient(W/2,H*.64,20,W/2,H*.64,W*.58);glow.addColorStop(0,`hsla(${s.hue} 60% 38% / .24)`);glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(13,19,17,.98)';ctx.beginPath();ctx.moveTo(0,H*.36);for(let x=0;x<=W;x+=60){ctx.lineTo(x,H*.30+Math.sin(x*.014+CFG.seed)*16+tgV7Seeded(x)*22)}ctx.lineTo(W,0);ctx.lineTo(0,0);ctx.closePath();ctx.fill();}
function tgV7Road(){ctx.strokeStyle='rgba(151,127,90,.40)';ctx.lineWidth=48;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(W*.5,H);ctx.quadraticCurveTo(W*.58,H*.68,W*.5,H*.30);ctx.stroke();ctx.strokeStyle='rgba(224,204,167,.10)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(W*.5,H);ctx.quadraticCurveTo(W*.58,H*.68,W*.5,H*.30);ctx.stroke()}
function tgV7Hut(p,s,i){let w=38*p.s,h=31*p.s,roof=19*p.s,x=p.x,y=p.y;ctx.save();ctx.shadowBlur=12*p.s;ctx.shadowColor='rgba(0,0,0,.48)';ctx.fillStyle=`hsl(${26+Math.floor(tgV7Seeded(i)*10)} 22% ${24+Math.floor(tgV7Seeded(i+2)*8)}%)`;ctx.fillRect(x-w/2,y-h,w,h);ctx.fillStyle=`hsl(${18+Math.floor(tgV7Seeded(i+4)*9)} 32% 19%)`;ctx.beginPath();ctx.moveTo(x-w*.62,y-h);ctx.lineTo(x,y-h-roof);ctx.lineTo(x+w*.62,y-h);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(255,183,94,.58)';ctx.fillRect(x-w*.08,y-h*.48,w*.16,h*.28);if(i===0&&s.culture){ctx.strokeStyle=`hsl(${s.hue} 80% 72%)`;ctx.lineWidth=2*p.s;ctx.beginPath();ctx.moveTo(x+w*.58,y-h-roof*.3);ctx.lineTo(x+w*.58,y-h-roof*1.9);ctx.stroke();ctx.fillStyle=`hsl(${s.hue} 75% 62%)`;ctx.beginPath();ctx.moveTo(x+w*.58,y-h-roof*1.85);ctx.lineTo(x+w*1.02,y-h-roof*1.55);ctx.lineTo(x+w*.58,y-h-roof*1.25);ctx.closePath();ctx.fill()}ctx.restore()}
function tgV7Monument(s){if(!s.monument)return;let p=tgV7Proj(-95,40);ctx.save();ctx.fillStyle='rgba(210,205,181,.90)';ctx.shadowBlur=18;ctx.shadowColor=`hsla(${s.hue} 80% 70% / .38)`;if(s.monument.type==='stone ring'){ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=6*p.s;ctx.beginPath();ctx.arc(p.x,p.y-22*p.s,18*p.s,0,TAU);ctx.stroke()}else{ctx.fillRect(p.x-5*p.s,p.y-42*p.s,10*p.s,42*p.s)}ctx.restore()}
function tgV7Fire(s){let p=tgV7Proj(20,45),f=.5+.5*Math.sin(performance.now()*.012);ctx.save();ctx.fillStyle=`rgba(255,160,55,${.55+.2*f})`;ctx.shadowBlur=20+10*f;ctx.shadowColor='rgba(255,126,33,.9)';ctx.beginPath();ctx.arc(p.x,p.y,5+2*f,0,TAU);ctx.fill();ctx.restore();let smokeT=(performance.now()*.00008)%1;for(let i=0;i<4;i++){let t=(smokeT+i*.23)%1;ctx.fillStyle=`rgba(185,195,188,${.11*(1-t)})`;ctx.beginPath();ctx.arc(p.x+Math.sin((t+i)*8)*8,p.y-14-58*t,5+10*t,0,TAU);ctx.fill()}}
function tgV7Trees(){for(let i=0;i<10;i++){let side=i%2?1:-1,x=(side>0?W*.80:W*.20)+side*tgV7Seeded(i+71)*W*.16,y=H*.42+tgV7Seeded(i+91)*H*.5,s=.7+tgV7Seeded(i+37)*1.1;ctx.save();ctx.fillStyle='rgba(9,17,13,.96)';ctx.fillRect(x-3*s,y-36*s,6*s,40*s);ctx.beginPath();ctx.arc(x,y-46*s,20*s,0,TAU);ctx.arc(x-13*s,y-36*s,15*s,0,TAU);ctx.arc(x+12*s,y-35*s,16*s,0,TAU);ctx.fill();ctx.restore()}}
function tgV7Caravans(s){let cs=world.caravans.filter(c=>c.to===s||c.from===s).slice(0,3);for(let i=0;i<cs.length;i++){let c=cs[i],p=clamp(c.t/c.dur,0,1),toward=c.to===s?p:1-p,y=-150+p*330,x=(i-1)*26+Math.sin((p+i)*TAU)*10,pr=tgV7Proj(x,y);ctx.save();ctx.fillStyle=c.kind==='trade'?'#ffe08a':'#b8ddff';ctx.shadowBlur=10;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(pr.x,pr.y,4*pr.s,0,TAU);ctx.fill();ctx.strokeStyle='rgba(235,245,240,.5)';ctx.beginPath();ctx.moveTo(pr.x,pr.y);ctx.lineTo(pr.x,pr.y+12*pr.s);ctx.stroke();ctx.restore()}}
function tgV7People(s){let members=world.agents.filter(a=>a.alive&&a.home===s).slice(0,Math.min(18,s.pop)),hits=[];for(let i=0;i<members.length;i++){let a=members[i],t=(day*.12+i*.137)%1,x=Math.sin((t+i)*TAU)*118+(i%3-1)*28,y=115+Math.cos((t*.8+i)*TAU)*140,p=tgV7Proj(x,y);hits.push({a,x:p.x,y:p.y,r:10*p.s});ctx.save();ctx.fillStyle=a.dynasty?`hsl(${a.dynasty.hue} 78% 74%)`:'#d9eee5';ctx.shadowBlur=tgV7Hover===a?12:5;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(p.x,p.y-8*p.s,(tgV7Hover===a?4:3)*p.s,0,TAU);ctx.fill();ctx.strokeStyle='rgba(220,236,228,.74)';ctx.lineWidth=2*p.s;ctx.beginPath();ctx.moveTo(p.x,p.y-5*p.s);ctx.lineTo(p.x,p.y+8*p.s);ctx.stroke();ctx.restore()}return hits}
let tgV7Hits=[];
function tgV7Weather(){if(!world.weather)return;let night=.5-.5*Math.cos((day%1)*TAU),rain=world.weather.kind==='rain'||world.weather.kind==='storm';if(rain){ctx.strokeStyle='rgba(190,220,230,.18)';ctx.lineWidth=1;for(let i=0;i<65;i++){let x=(i*83+performance.now()*.18)%W,y=(i*47+performance.now()*.32)%H;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-5,y+12);ctx.stroke()}}if(night>.52){ctx.fillStyle=`rgba(4,8,14,${(night-.52)*.55})`;ctx.fillRect(0,0,W,H)}}
function tgV7Close(){let s=tgV7Settlement;if(!s||s.abandoned){tgV7Exit();return}tgV7Ground(s);tgV7Road();let layout=tgV7Layout(s);for(const h of layout){let p=tgV7Proj(h.x,h.y);tgV7Hut(p,s,h.i)}tgV7Monument(s);tgV7Caravans(s);tgV7Fire(s);tgV7Hits=tgV7People(s);tgV7Trees();tgV7Weather();ctx.fillStyle='rgba(235,255,246,.92)';ctx.font='800 12px ui-monospace';ctx.fillText(`${s.culture?.sigil||'⌂'} ${s.n}`,22,30);ctx.font='9px ui-monospace';ctx.fillStyle='rgba(210,232,224,.66)';ctx.fillText(`${s.culture?.name||'settlement'} · pop ${s.pop} · stores ${Math.round((s.store||0)*100)}%`,22,47);if(s.founder)ctx.fillText(`founded by ${s.founder.n}`,22,62)}
canvas.addEventListener('mousemove',e=>{if(tgV7Mode!=='close')return;let r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,best=null,bd=Infinity;for(const h of tgV7Hits){let d=(h.x-x)**2+(h.y-y)**2;if(d<h.r*h.r&&d<bd){bd=d;best=h.a}}tgV7Hover=best;canvas.style.cursor=best?'pointer':'default'});
canvas.addEventListener('click',e=>{if(tgV7Mode!=='close')return;let r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,best=null,bd=Infinity;for(const h of tgV7Hits){let d=(h.x-x)**2+(h.y-y)**2;if(d<h.r*h.r&&d<bd){bd=d;best=h.a}}if(best){e.preventDefault();e.stopImmediatePropagation();showCard(best)}},true);
const tgV7BaseDraw=draw;draw=function(){if(tgV7Mode==='world'){tgV7BaseDraw()}else{tgV7Close()}if(tgV7Fade>0){ctx.fillStyle=`rgba(5,8,10,${Math.min(.75,tgV7Fade)})`;ctx.fillRect(0,0,W,H);tgV7Fade=Math.max(0,tgV7Fade-.055)}};
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&tgV7Mode==='close'){e.preventDefault();tgV7Exit()}});
log('⌂ Under the Glass is alive: settlements can now be entered, inspected, and watched up close.');