// Tiny Gods v0.7 — Under the Glass
// Adds a close 2.5D settlement view derived from live simulation state.
let tgV7Mode='world',tgV7Settlement=null,tgV7Fade=0,tgV7LastTap=0;
const tgV7Style=document.createElement('style');tgV7Style.textContent=`#underGlassHud{position:absolute;left:50%;bottom:18px;transform:translateX(-50%);display:flex;gap:8px;align-items:center;z-index:20}#underGlassHud button{border:1px solid rgba(255,255,255,.16);background:rgba(8,14,18,.78);color:#eafff6;border-radius:999px;padding:8px 12px;font:800 9px ui-monospace,monospace;letter-spacing:.1em;cursor:pointer;backdrop-filter:blur(8px)}#underGlassHud .place{font:800 9px ui-monospace,monospace;color:#c8ffea;letter-spacing:.12em}#underGlassHint{position:absolute;left:50%;bottom:58px;transform:translateX(-50%);font:700 8px ui-monospace,monospace;color:rgba(220,244,235,.6);letter-spacing:.1em;pointer-events:none}body.tg-close #stats,body.tg-close #historyStrip,body.tg-close #legendHall,body.tg-close #dynastyLedger{opacity:.15;pointer-events:none}body.tg-close #agentcard{z-index:30}`;document.head.appendChild(tgV7Style);
const tgV7Hud=document.createElement('div');tgV7Hud.id='underGlassHud';tgV7Hud.className='glass';tgV7Hud.style.display='none';tgV7Hud.innerHTML='<span class="place" id="underGlassPlace"></span><button id="underGlassExit">↑ RETURN TO WORLD</button>';document.getElementById('wrap').appendChild(tgV7Hud);
const tgV7Hint=document.createElement('div');tgV7Hint.id='underGlassHint';tgV7Hint.textContent='DOUBLE-CLICK A SETTLEMENT TO ENTER';document.getElementById('wrap').appendChild(tgV7Hint);
document.getElementById('underGlassExit').onclick=()=>tgV7Exit();
function tgV7Enter(s){if(!s||s.abandoned||s.pop<1)return;tgV7Settlement=s;tgV7Mode='close';tgV7Fade=1;document.body.classList.add('tg-close');tgV7Hud.style.display='flex';document.getElementById('underGlassPlace').textContent=`${s.culture?.sigil||'⌂'} ${s.n.toUpperCase()}`;tgV7Hint.style.display='none';log(`⌂ You descended into ${s.n}.`)}
function tgV7Exit(){tgV7Mode='world';tgV7Fade=1;document.body.classList.remove('tg-close');tgV7Hud.style.display='none';tgV7Hint.style.display='';tgV7Settlement=null;document.getElementById('agentcard').classList.remove('on')}
canvas.addEventListener('dblclick',e=>{if(tgV7Mode==='close')return;const r=canvas.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top,wx=(sx-W/2)/camera.z+world.w/2+camera.x,wy=(sy-H/2)/camera.z+world.h/2+camera.y;let best=null,bd=55*55;for(const s of world.settlements){if(s.abandoned||s.pop<1)continue;let d=(s.x-wx)**2+(s.y-wy)**2;if(d<bd){bd=d;best=s}}if(best){e.preventDefault();e.stopImmediatePropagation();tgV7Enter(best)}},true);
function tgV7Seeded(n){let x=Math.sin(n*12.9898+CFG.seed*.0001)*43758.5453;return x-Math.floor(x)}
function tgV7Layout(s){let count=Math.max(4,Math.min(18,Math.ceil(s.pop/2.2))),items=[];for(let i=0;i<count;i++){let ring=Math.floor(Math.sqrt(i))+1,ang=tgV7Seeded(i+s.id*31)*TAU,rrr=70+ring*38+tgV7Seeded(i*7+s.id)*22;items.push({x:Math.cos(ang)*rrr,y:Math.sin(ang)*rrr*.48,z:tgV7Seeded(i*13+s.id),i})}return items.sort((a,b)=>a.y-b.y)}
function tgV7Proj(x,y){let horizon=H*.31,depth=(y+260)/520,scale=.55+depth*.78;return{x:W/2+x*scale,y:horizon+depth*(H*.58),s:scale}}
function tgV7Ground(s){let g=ctx.createLinearGradient(0,H*.25,0,H);g.addColorStop(0,'#27332f');g.addColorStop(.55,'#18231f');g.addColorStop(1,'#0b100e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);let glow=ctx.createRadialGradient(W/2,H*.62,30,W/2,H*.62,W*.52);glow.addColorStop(0,`hsla(${s.hue} 55% 35% / .22)`);glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(15,22,20,.95)';ctx.beginPath();ctx.moveTo(0,H*.36);for(let x=0;x<=W;x+=70){ctx.lineTo(x,H*.31+Math.sin(x*.014+CFG.seed)*18+tgV7Seeded(x)*24)}ctx.lineTo(W,0);ctx.lineTo(0,0);ctx.closePath();ctx.fill();}
function tgV7Road(){ctx.strokeStyle='rgba(145,124,91,.38)';ctx.lineWidth=42;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(W*.5,H);ctx.quadraticCurveTo(W*.56,H*.68,W*.5,H*.32);ctx.stroke();ctx.strokeStyle='rgba(220,199,157,.09)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(W*.5,H);ctx.quadraticCurveTo(W*.56,H*.68,W*.5,H*.32);ctx.stroke()}
function tgV7Hut(p,s,i){let w=36*p.s,h=29*p.s,roof=18*p.s,x=p.x,y=p.y;ctx.save();ctx.shadowBlur=10*p.s;ctx.shadowColor='rgba(0,0,0,.45)';ctx.fillStyle=`hsl(${26+Math.floor(tgV7Seeded(i)*10)} 22% ${24+Math.floor(tgV7Seeded(i+2)*8)}%)`;ctx.fillRect(x-w/2,y-h,w,h);ctx.fillStyle=`hsl(${18+Math.floor(tgV7Seeded(i+4)*9)} 32% 19%)`;ctx.beginPath();ctx.moveTo(x-w*.62,y-h);ctx.lineTo(x,y-h-roof);ctx.lineTo(x+w*.62,y-h);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(255,183,94,.55)';ctx.fillRect(x-w*.08,y-h*.48,w*.16,h*.28);if(i===0&&s.culture){ctx.strokeStyle=`hsl(${s.hue} 80% 72%)`;ctx.lineWidth=2*p.s;ctx.beginPath();ctx.moveTo(x+w*.58,y-h-roof*.3);ctx.lineTo(x+w*.58,y-h-roof*1.9);ctx.stroke();ctx.fillStyle=`hsl(${s.hue} 75% 62%)`;ctx.beginPath();ctx.moveTo(x+w*.58,y-h-roof*1.85);ctx.lineTo(x+w*1.02,y-h-roof*1.55);ctx.lineTo(x+w*.58,y-h-roof*1.25);ctx.closePath();ctx.fill()};ctx.restore()}
function tgV7Monument(s){if(!s.monument)return;let p=tgV7Proj(-95,40);ctx.save();ctx.fillStyle='rgba(210,205,181,.86)';ctx.shadowBlur=18;ctx.shadowColor=`hsla(${s.hue} 80% 70% / .35)`;if(s.monument.type==='stone ring'){ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=6*p.s;ctx.beginPath();ctx.arc(p.x,p.y-22*p.s,18*p.s,0,TAU);ctx.stroke()}else{ctx.fillRect(p.x-5*p.s,p.y-42*p.s,10*p.s,42*p.s)}ctx.restore()}
function tgV7People(s){let members=world.agents.filter(a=>a.alive&&a.home===s).slice(0,Math.min(16,s.pop));for(let i=0;i<members.length;i++){let a=members[i],t=(day*.12+i*.137)%1,x=Math.sin((t+i)*TAU)*115+(i%3-1)*28,y=120+Math.cos((t*.8+i)*TAU)*135,p=tgV7Proj(x,y);ctx.save();ctx.fillStyle=a.dynasty?`hsl(${a.dynasty.hue} 78% 74%)`:'#d9eee5';ctx.shadowBlur=5;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(p.x,p.y-8*p.s,3*p.s,0,TAU);ctx.fill();ctx.strokeStyle='rgba(220,236,228,.72)';ctx.lineWidth=2*p.s;ctx.beginPath();ctx.moveTo(p.x,p.y-5*p.s);ctx.lineTo(p.x,p.y+8*p.s);ctx.stroke();ctx.restore()}}
function tgV7Close(){let s=tgV7Settlement;if(!s||s.abandoned){tgV7Exit();return}tgV7Ground(s);tgV7Road();let layout=tgV7Layout(s);for(const h of layout){let p=tgV7Proj(h.x,h.y);tgV7Hut(p,s,h.i)}tgV7Monument(s);tgV7People(s);let night=.5-.5*Math.cos((day%1)*TAU);if(night>.55){let p=tgV7Proj(25,35),g=ctx.createRadialGradient(p.x,p.y,2,p.x,p.y,90*p.s);g.addColorStop(0,'rgba(255,174,76,.48)');g.addColorStop(1,'rgba(255,120,30,0)');ctx.fillStyle=g;ctx.fillRect(p.x-100,p.y-100,200,200)}ctx.fillStyle='rgba(235,255,246,.9)';ctx.font='800 12px ui-monospace';ctx.fillText(`${s.culture?.sigil||'⌂'} ${s.n}`,22,30);ctx.font='9px ui-monospace';ctx.fillStyle='rgba(210,232,224,.65)';ctx.fillText(`${s.culture?.name||'settlement'} · pop ${s.pop} · stores ${Math.round((s.store||0)*100)}%`,22,47);if(s.founder){ctx.fillText(`founded by ${s.founder.n}`,22,62)}}
const tgV7BaseDraw=draw;draw=function(){if(tgV7Mode==='world'){tgV7BaseDraw()}else{tgV7Close()}if(tgV7Fade>0){ctx.fillStyle=`rgba(5,8,10,${Math.min(.75,tgV7Fade)})`;ctx.fillRect(0,0,W,H);tgV7Fade=Math.max(0,tgV7Fade-.055)}};
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&tgV7Mode==='close'){e.preventDefault();tgV7Exit()}});
log('⌂ Under the Glass is ready: double-click a settlement to descend into it.');